-- Trusted local owner fixtures only; every grant/opening/guard change rolls back.
\connect postgres supabase_admin
begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select is((select enabled from public.trip_source_command_gate),false,'Source activation CLOSED');
select is((select count(*)::int from public.trip_source_operations),0,'no installed operations');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_operations'::regclass),'operations forced RLS');
select ok(not exists(select 1 from pg_roles where rolname in ('otr_trip_source_writer','otr_trip_source_command_gateway','otr_trip_source_operation_reader') and (rolcanlogin or rolsuper or rolcreatedb or rolcreaterole or rolinherit or rolbypassrls or rolreplication)),'reserved identities cannot login or bypass');
select ok(not exists(select 1 from pg_auth_members where roleid in ('otr_trip_source_writer'::regrole,'otr_trip_source_command_gateway'::regrole,'otr_trip_source_operation_reader'::regrole) and (set_option or inherit_option)),'no runtime SET ROLE or inherited membership');
select is((select count(*)::int from pg_proc where proowner='otr_trip_source_writer'::regrole),7,'seven fixed command owners');
select is((select count(*)::int from pg_proc where pronamespace='public'::regnamespace and has_function_privilege('otr_trip_source_command_gateway',oid,'EXECUTE') and proname like 'trip_source_%'),8,'gateway only seven commands and exact lookup');
select ok(not has_function_privilege('otr_trip_source_command_gateway','public.trip_source_finalize(uuid,uuid,uuid,uuid,text,text,bigint,uuid,jsonb)','EXECUTE'),'gateway cannot submit semantic proof');
select ok(not has_function_privilege('otr_trip_source_command_gateway','public.trip_source_attempt_observe(uuid,text,text,bigint,uuid,text)','EXECUTE'),'gateway cannot assert quiescence');
select ok(not exists(select 1 from pg_namespace where nspname not in ('pg_catalog','information_schema') and nspname !~ '^pg_(toast|temp)' and (has_schema_privilege('otr_trip_source_writer',oid,'CREATE') or has_schema_privilege('otr_trip_source_command_gateway',oid,'CREATE') or has_schema_privilege('otr_trip_source_operation_reader',oid,'CREATE'))),'no application schema CREATE');
create temporary table ci3d_before as select jsonb_build_object(
 'a',(select jsonb_agg(to_jsonb(x) order by id) from public.journey_members x),
 'b',(select jsonb_agg(to_jsonb(x) order by id) from public.itinerary_events x),
 'br',(select jsonb_agg(to_jsonb(x) order by trip_id,actor_account_id,operation_key) from public.trip_event_operation_receipts x),
 'expense',(select jsonb_agg(to_jsonb(x) order by id) from public.expenses x),
 'receipt',(select jsonb_agg(to_jsonb(x) order by id) from public.receipt_assets x),
 'payment',(select jsonb_agg(to_jsonb(x) order by id) from public.personal_settlement_payment_records x),
 'buckets',(select jsonb_agg(to_jsonb(x) order by id) from storage.buckets x)) value;
create temporary table ci3d_inputs(n integer primary key,raw text);
create temporary table ci3d_results(n integer primary key,value jsonb);
grant select,insert,update on ci3d_inputs,ci3d_results to public;
create function pg_temp.cid(n integer) returns uuid language sql immutable as $$ select ('cd000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
create function pg_temp.cinput(family text,n integer,sid integer,rid integer,sbase bigint default 1,rbase bigint default 1,mat bigint default 1,kind text default 'BINARY',content text default 'synthetic',target_trip uuid default '10000000-0000-4000-8000-000000000001') returns text
language plpgsql security definer set search_path=pg_catalog as $$ declare j jsonb; p jsonb; d jsonb; cap jsonb; input jsonb; h text; prev bigint; rev bigint;
begin
 d:=jsonb_build_object('id',pg_temp.cid(rid),'material_kind',kind,'original_filename',case when kind='BINARY' then 'synthetic.pdf' end,'part_key',null,'mime_type',case when kind='BINARY' then 'application/pdf' end,'encoding',case when kind<>'BINARY' then 'UTF-8' end,'payload_sha256',encode(extensions.digest(content,'sha256'),'hex'),'byte_count',octet_length(content),'text_content',case when kind='TEXT' then content end,'locator_uri',case when kind='LOCATOR' then content end);
 input:=jsonb_build_object('source_kind',case kind when 'BINARY' then 'FILE' when 'TEXT' then 'TEXT' else 'URL' end,'acquisition_channel',case kind when 'BINARY' then 'FILES' when 'TEXT' then 'PASTE' else 'URL_CAPTURE' end,'captured_at',null,'capture_time_basis','UNKNOWN');
 rev:=case when family='ACQUIRE_SOURCE' then 1 else mat+1 end; prev:=case when family='REPLACE_MATERIAL' then mat end;
 cap:=jsonb_build_object('completeness','AS_SUPPLIED','capture_sha256',public.trip_source_hash('otr-source-capture-v1',jsonb_build_array(1,pg_temp.cid(sid),rev,prev,jsonb_build_array(pg_temp.cid(rid)),'AS_SUPPLIED',case when family='ACQUIRE_SOURCE' then 'ACQUISITION' else 'REPLACEMENT' end,null,null)));
 p:=jsonb_build_object('material_revision',mat,'expected_source_row_revision',sbase,'expected_source_state',jsonb_build_object('lifecycle','ACTIVE','retention_state','RETAINED'),'representation_id',pg_temp.cid(rid),'expected_representation_row_revision',rbase,'expected_representation_state',jsonb_build_object('remote_state',case family when 'MARK_REPRESENTATION_LOST' then 'VERIFIED' when 'RECOVER_REPRESENTATION' then 'LOST' else 'PENDING' end,'retention_state','RETAINED'));
 if family='ACQUIRE_SOURCE' then
  p:=jsonb_build_object('acquisition_key','op-'||n,'acquisition_sha256',public.trip_source_hash('otr-source-acquisition-v1',jsonb_build_array(1,target_trip,'00000000-0000-4000-8000-000000000001',pg_temp.cid(sid),'op-'||n,input->'source_kind',input->'acquisition_channel',null,'UNKNOWN',cap->'capture_sha256',jsonb_build_array(d->'id',d->'material_kind',d->'original_filename',d->'part_key',d->'mime_type',d->'encoding',d->'payload_sha256',d->'byte_count',d->'text_content',d->'locator_uri'))),'source_input',input,'capture',cap,'original',d);
 elsif family='REPLACE_MATERIAL' then
  p:=(p-array['representation_id','expected_representation_row_revision','expected_representation_state'])||jsonb_build_object('expected_current_material_revision',mat,'capture',cap,'original',d);
 end if;
 if family='UPLOAD_ORIGINAL' then p:=p||jsonb_build_object('parent_operation_id',pg_temp.cid(20),'payload_sha256',d->'payload_sha256','byte_count',d->'byte_count','mime_type',d->'mime_type'); end if;
 j:=jsonb_build_object('contract_version',1,'command',family,'operation_id',pg_temp.cid(n),'operation_key','op-'||n,'actor_account_id','00000000-0000-4000-8000-000000000001','trip_id',target_trip,'source_id',pg_temp.cid(sid),'payload',p);
 if family='UPLOAD_ORIGINAL' then h:=public.trip_source_hash('otr-source-upload-v1',jsonb_build_array(1,j->'operation_id',j->'operation_key',j->'actor_account_id',j->'trip_id',j->'source_id')||public.trip_source_payload_tuple(family,p)); else
 h:=public.trip_source_hash('otr-source-command-v1',jsonb_build_array(1,family,j->'operation_id',j->'operation_key',j->'actor_account_id',j->'trip_id',j->'source_id',public.trip_source_payload_tuple(family,p)));
 end if;
 return (j||jsonb_build_object('operation_sha256',h))::text;
end $$;
create function pg_temp.ccall(family text,n integer) returns jsonb language plpgsql as $$ declare raw text; actor uuid:='00000000-0000-4000-8000-000000000001'; begin
 select i.raw into strict raw from ci3d_inputs i where i.n=ccall.n;
 case family
 when 'ACQUIRE_SOURCE' then return public.trip_source_acquire_source(actor,raw);
 when 'PREPARE_REPRESENTATION' then return public.trip_source_prepare_representation(actor,raw);
 when 'REPLACE_MATERIAL' then return public.trip_source_replace_material(actor,raw);
 when 'VERIFY_REPRESENTATION' then return public.trip_source_verify_representation(actor,raw);
 when 'MARK_REPRESENTATION_LOST' then return public.trip_source_mark_representation_lost(actor,raw);
 when 'RECOVER_REPRESENTATION' then return public.trip_source_recover_representation(actor,raw);
 when 'UPLOAD_ORIGINAL' then return public.trip_source_upload_original(actor,raw);
 end case; end $$;
create function pg_temp.clook(n integer) returns jsonb language sql as $$ select public.trip_source_operation_lookup('00000000-0000-4000-8000-000000000001',(raw::jsonb->>'trip_id')::uuid,(raw::jsonb->>'source_id')::uuid,pg_temp.cid(n),raw::jsonb->>'operation_key',raw::jsonb->>'operation_sha256') from ci3d_inputs where ci3d_inputs.n=clook.n $$;
create function pg_temp.cstart(n integer,phase text,generation bigint,prior integer,attempt integer) returns jsonb language sql as $$ select public.trip_source_attempt_start('00000000-0000-4000-8000-000000000001',(raw::jsonb->>'trip_id')::uuid,(raw::jsonb->>'source_id')::uuid,pg_temp.cid(n),raw::jsonb->>'operation_key',raw::jsonb->>'operation_sha256',phase,generation,case when prior is not null then pg_temp.cid(prior) end,pg_temp.cid(attempt)) from ci3d_inputs where ci3d_inputs.n=cstart.n $$;
create function pg_temp.cobserve(n integer,phase text,generation bigint,attempt integer,observation text) returns jsonb language sql as $$ select public.trip_source_attempt_observe(pg_temp.cid(n),raw::jsonb->>'operation_sha256',phase,generation,pg_temp.cid(attempt),observation) from ci3d_inputs where ci3d_inputs.n=cobserve.n $$;
create function pg_temp.cfinal(n integer,generation bigint,attempt integer,kind text default 'MATCH') returns jsonb language sql as $$ select public.trip_source_finalize(o.actor_account_id,o.trip_id,o.source_id,o.id,o.operation_key,o.operation_sha256,generation,pg_temp.cid(attempt),jsonb_build_object('operation_id',o.id,'attempt_id',pg_temp.cid(attempt),'attempt_generation',generation,'kind',kind,'payload_sha256',case when kind<>'DEFINITE_MISSING' then o.bound_payload_sha256 end,'byte_count',case when kind<>'DEFINITE_MISSING' then o.bound_byte_count end,'mime_type',case when kind<>'DEFINITE_MISSING' then o.bound_mime_type end,'observed_at',public.trip_event_utc_timestamp(o.io_finished_at))) from public.trip_source_operations o where o.id=pg_temp.cid(n) $$;
insert into ci3d_inputs values(1,pg_temp.cinput('ACQUIRE_SOURCE',1,100,101));
insert into ci3d_inputs values(2,pg_temp.cinput('PREPARE_REPRESENTATION',2,100,101));
insert into ci3d_inputs values(3,pg_temp.cinput('VERIFY_REPRESENTATION',3,100,101));
insert into ci3d_inputs values(4,pg_temp.cinput('REPLACE_MATERIAL',4,100,101));
insert into ci3d_inputs values(5,pg_temp.cinput('MARK_REPRESENTATION_LOST',5,100,101));
insert into ci3d_inputs values(6,pg_temp.cinput('RECOVER_REPRESENTATION',6,100,101));
insert into ci3d_inputs values(7,pg_temp.cinput('UPLOAD_ORIGINAL',7,100,101));
grant usage on schema extensions to otr_trip_source_command_gateway,otr_trip_source_writer;
reset role;
set session authorization otr_trip_source_command_gateway;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select set_config('otr.source_enabled','true',true);
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',1)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed ACQUIRE_SOURCE consumes no key');
select throws_ok($q$select pg_temp.ccall('PREPARE_REPRESENTATION',2)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed PREPARE_REPRESENTATION consumes no key');
select throws_ok($q$select pg_temp.ccall('VERIFY_REPRESENTATION',3)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed VERIFY_REPRESENTATION consumes no key');
select throws_ok($q$select pg_temp.ccall('REPLACE_MATERIAL',4)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed REPLACE_MATERIAL consumes no key');
select throws_ok($q$select pg_temp.ccall('MARK_REPRESENTATION_LOST',5)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed MARK_REPRESENTATION_LOST consumes no key');
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',6)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed RECOVER_REPRESENTATION consumes no key');
select throws_ok($q$select pg_temp.ccall('UPLOAD_ORIGINAL',7)$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','closed internal UPLOAD consumes no key');
reset session authorization; set local role postgres;
-- C-I3H adds an operation FK. Explicitly include its child so FK validation
-- cannot mask the canonical zero-row TRUNCATE statement guard (rollback-only).
reset role; grant truncate on public.trip_source_execution_attempts to anon,authenticated,service_role,otr_trip_source_writer; set local role postgres;
grant select,insert,update,delete,truncate on public.trip_source_operations to anon;
set local role anon;
select throws_ok($q$insert into public.trip_source_operations select * from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','anon zero-row/bulk operation DML guarded');
select throws_ok($q$update public.trip_source_operations set phase=phase where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','anon zero-row/bulk operation DML guarded');
select throws_ok($q$delete from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','anon zero-row/bulk operation DML guarded');
select throws_ok($q$truncate public.trip_source_operations,public.trip_source_execution_attempts$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','anon zero-row/bulk operation DML guarded');
reset role; set local role postgres; revoke select,insert,update,delete,truncate on public.trip_source_operations from anon;
grant select,insert,update,delete,truncate on public.trip_source_operations to authenticated;
set local role authenticated;
select throws_ok($q$insert into public.trip_source_operations select * from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','authenticated zero-row/bulk operation DML guarded');
select throws_ok($q$update public.trip_source_operations set phase=phase where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','authenticated zero-row/bulk operation DML guarded');
select throws_ok($q$delete from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','authenticated zero-row/bulk operation DML guarded');
select throws_ok($q$truncate public.trip_source_operations,public.trip_source_execution_attempts$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','authenticated zero-row/bulk operation DML guarded');
reset role; set local role postgres; revoke select,insert,update,delete,truncate on public.trip_source_operations from authenticated;
grant select,insert,update,delete,truncate on public.trip_source_operations to service_role;
set local role service_role;
select throws_ok($q$insert into public.trip_source_operations select * from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','service_role zero-row/bulk operation DML guarded');
select throws_ok($q$update public.trip_source_operations set phase=phase where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','service_role zero-row/bulk operation DML guarded');
select throws_ok($q$delete from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','service_role zero-row/bulk operation DML guarded');
select throws_ok($q$truncate public.trip_source_operations,public.trip_source_execution_attempts$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','service_role zero-row/bulk operation DML guarded');
reset role; set local role postgres; revoke select,insert,update,delete,truncate on public.trip_source_operations from service_role;
grant select,insert,update,delete,truncate on public.trip_source_operations to otr_trip_source_writer;
set local role otr_trip_source_writer;
select throws_ok($q$insert into public.trip_source_operations select * from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','otr_trip_source_writer zero-row/bulk operation DML guarded');
select throws_ok($q$update public.trip_source_operations set phase=phase where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','otr_trip_source_writer zero-row/bulk operation DML guarded');
select throws_ok($q$delete from public.trip_source_operations where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','otr_trip_source_writer zero-row/bulk operation DML guarded');
select throws_ok($q$truncate public.trip_source_operations,public.trip_source_execution_attempts$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','otr_trip_source_writer zero-row/bulk operation DML guarded');
reset role; set local role postgres; revoke select,insert,update,delete,truncate on public.trip_source_operations from otr_trip_source_writer;
set local role anon;
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',1)$q$,'42501',null,'anon ACQUIRE_SOURCE lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('PREPARE_REPRESENTATION',2)$q$,'42501',null,'anon PREPARE_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('VERIFY_REPRESENTATION',3)$q$,'42501',null,'anon VERIFY_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('REPLACE_MATERIAL',4)$q$,'42501',null,'anon REPLACE_MATERIAL lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('MARK_REPRESENTATION_LOST',5)$q$,'42501',null,'anon MARK_REPRESENTATION_LOST lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',6)$q$,'42501',null,'anon RECOVER_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('UPLOAD_ORIGINAL',7)$q$,'42501',null,'anon UPLOAD_ORIGINAL lacks semantic authority');
reset role; set local role postgres;
set local role authenticated;
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',1)$q$,'42501',null,'authenticated ACQUIRE_SOURCE lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('PREPARE_REPRESENTATION',2)$q$,'42501',null,'authenticated PREPARE_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('VERIFY_REPRESENTATION',3)$q$,'42501',null,'authenticated VERIFY_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('REPLACE_MATERIAL',4)$q$,'42501',null,'authenticated REPLACE_MATERIAL lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('MARK_REPRESENTATION_LOST',5)$q$,'42501',null,'authenticated MARK_REPRESENTATION_LOST lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',6)$q$,'42501',null,'authenticated RECOVER_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('UPLOAD_ORIGINAL',7)$q$,'42501',null,'authenticated UPLOAD_ORIGINAL lacks semantic authority');
reset role; set local role postgres;
set local role service_role;
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',1)$q$,'42501',null,'service_role ACQUIRE_SOURCE lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('PREPARE_REPRESENTATION',2)$q$,'42501',null,'service_role PREPARE_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('VERIFY_REPRESENTATION',3)$q$,'42501',null,'service_role VERIFY_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('REPLACE_MATERIAL',4)$q$,'42501',null,'service_role REPLACE_MATERIAL lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('MARK_REPRESENTATION_LOST',5)$q$,'42501',null,'service_role MARK_REPRESENTATION_LOST lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',6)$q$,'42501',null,'service_role RECOVER_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('UPLOAD_ORIGINAL',7)$q$,'42501',null,'service_role UPLOAD_ORIGINAL lacks semantic authority');
reset role; set local role postgres;
set local role otr_trip_source_writer;
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',1)$q$,'42501',null,'otr_trip_source_writer ACQUIRE_SOURCE lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('PREPARE_REPRESENTATION',2)$q$,'42501',null,'otr_trip_source_writer PREPARE_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('VERIFY_REPRESENTATION',3)$q$,'42501',null,'otr_trip_source_writer VERIFY_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('REPLACE_MATERIAL',4)$q$,'42501',null,'otr_trip_source_writer REPLACE_MATERIAL lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('MARK_REPRESENTATION_LOST',5)$q$,'42501',null,'otr_trip_source_writer MARK_REPRESENTATION_LOST lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',6)$q$,'42501',null,'otr_trip_source_writer RECOVER_REPRESENTATION lacks semantic authority');
select throws_ok($q$select pg_temp.ccall('UPLOAD_ORIGINAL',7)$q$,'42501',null,'otr_trip_source_writer UPLOAD_ORIGINAL lacks semantic authority');
reset role; set local role postgres;
select ok(not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in ('trip_source_request_purge','trip_source_finalize_purge','trip_source_redact_source','trip_source_redact_representation')),'no purge/redaction entrypoint installed');
select is((select count(*)::int from public.trip_source_operations),0,'closed probes left zero keys');
select throws_ok($q$update public.trip_source_command_gate set enabled=true$q$,'23514',null,'named closed gate rejects ordinary owner setter');
select throws_ok($q$select public.trip_source_command_codec('{"contract_version":1,"contract_version":1}')$q$,'P0001','INVALID_COMMAND','recursive raw duplicate key rejection');
select throws_ok($q$select public.trip_source_command_codec('{"n":9007199254740992}')$q$,'P0001','INVALID_COMMAND','unsafe number rejected before dispatch');
select throws_ok($q$select public.trip_source_command_codec('{"n":1e0}')$q$,'P0001','INVALID_COMMAND','exponent spellings rejected');
select throws_ok($q$select public.trip_source_command_codec('{"n":-0}')$q$,'P0001','INVALID_COMMAND','negative zero rejected');
select throws_ok($q$select public.trip_source_command_codec(repeat(' ',2097153))$q$,'P0001','INVALID_SOURCE_COMMAND','metadata envelope bounded');
-- Trusted opening is rolled back; runtime migration has no setter/DML grant.
alter table public.trip_source_command_gate drop constraint trip_source_gate_closed;
update public.trip_source_command_gate set enabled=true;
grant select,insert,update on public.trip_sources,public.trip_source_revisions,public.trip_source_representations,public.trip_source_actions,public.trip_source_operations to otr_trip_source_writer;
grant select,update on public.trips,public.trip_members,public.journey_members to otr_trip_source_writer;
grant execute on function public.trip_source_uuid_array_valid(uuid[],integer,integer) to otr_trip_source_writer;
alter table public.trip_sources disable trigger trip_source_mutation_guard;
alter table public.trip_sources disable trigger trip_source_statement_guard;
alter table public.trip_source_revisions disable trigger trip_source_mutation_guard;
alter table public.trip_source_revisions disable trigger trip_source_statement_guard;
alter table public.trip_source_representations disable trigger trip_source_mutation_guard;
alter table public.trip_source_representations disable trigger trip_source_statement_guard;
alter table public.trip_source_actions disable trigger trip_source_mutation_guard;
alter table public.trip_source_actions disable trigger trip_source_statement_guard;
create policy ci3d_fixture on public.trip_sources for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_revisions for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_representations for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_actions for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_operations for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trips for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_members for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.journey_members for all to otr_trip_source_writer using(true) with check(true);
grant otr_trip_source_writer to otr_trip_source_command_gateway with inherit false,set true;
insert into ci3d_inputs values(10,pg_temp.cinput('ACQUIRE_SOURCE',10,100,101)),(11,pg_temp.cinput('ACQUIRE_SOURCE',11,110,111)),(12,pg_temp.cinput('ACQUIRE_SOURCE',12,120,121,1,1,1,'TEXT','雪
exact'));
reset role; set session authorization otr_trip_source_command_gateway;
insert into ci3d_results values(10,pg_temp.ccall('ACQUIRE_SOURCE',10));
select is((select value->>'outcome' from ci3d_results where n=10),'APPLIED','atomic acquisition applies');
select is(pg_temp.ccall('ACQUIRE_SOURCE',10),(select value from ci3d_results where n=10),'response loss exact replay');
select is(pg_temp.clook(10),(select value from ci3d_results where n=10),'exact lookup immutable receipt');
insert into ci3d_results values(11,pg_temp.ccall('ACQUIRE_SOURCE',11)),(12,pg_temp.ccall('ACQUIRE_SOURCE',12));
select is((select value->>'result_remote_state' from ci3d_results where n=12),'NOT_APPLICABLE','inline UTF-8 no I/O');
reset session authorization; set local role postgres;
select is((select count(*)::int from public.trip_sources),3,'same bytes distinct intentional acquisitions');
select is((select count(*)::int from public.trip_source_revisions),3,'each acquisition exactly rev1');
select is((select count(*)::int from public.trip_source_representations),3,'one ORIGINAL per acquisition');
select is((select count(*)::int from public.trip_source_actions),3,'one ACQUIRE Action each');
set constraints all immediate; set constraints all deferred;
insert into ci3d_inputs values(13,pg_temp.cinput('ACQUIRE_SOURCE',10,100,101,1,1,1,'BINARY','changed'));
reset role; set session authorization otr_trip_source_command_gateway;
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',13)$q$,'23505','OPERATION_KEY_REUSED','same key changed bytes rejects');
set timezone='Pacific/Auckland';
select is(pg_temp.clook(10),(select value from ci3d_results where n=10),'historic receipt timezone independent');
set timezone='America/Los_Angeles';
select is(pg_temp.clook(10),(select value from ci3d_results where n=10),'UTC result digest stable across timezone');
reset session authorization; set local role postgres;
insert into ci3d_inputs values(20,pg_temp.cinput('PREPARE_REPRESENTATION',20,100,101)),(21,pg_temp.cinput('VERIFY_REPRESENTATION',21,100,101));
reset role; set session authorization otr_trip_source_command_gateway;
insert into ci3d_results values(20,pg_temp.ccall('PREPARE_REPRESENTATION',20));
select is((select value->>'outcome' from ci3d_results where n=20),'APPLIED','PREPARE persists receipt only');
reset role; reset session authorization; set local role postgres;
insert into ci3d_inputs values(23,pg_temp.cinput('UPLOAD_ORIGINAL',23,100,101));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('UPLOAD_ORIGINAL',23)->>'phase','ADMITTED','UPLOAD exact PREPARE binding admitted');
set role otr_trip_source_writer;
select is(pg_temp.cstart(23,'ADMITTED',1,null,231)->>'phase','IO_ACTIVE','upload ownership before any external I/O');
select is(pg_temp.cobserve(23,'IO_ACTIVE',1,231,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','upload trusted completion');
select is(pg_temp.cfinal(23,1,231)->>'result_remote_state','PENDING','upload-only receipt never means VERIFIED');
select is((select row_revision::int from public.trip_source_representations where id=pg_temp.cid(101)),1,'upload does not mutate Representation revision');
reset role;
insert into ci3d_results values(21,pg_temp.ccall('VERIFY_REPRESENTATION',21));
select is((select value->>'phase' from ci3d_results where n=21),'ADMITTED','verification commits admission without proof');
set role otr_trip_source_writer;
select is(pg_temp.cstart(21,'ADMITTED',1,null,201)->>'phase','IO_ACTIVE','exact first attempt generation 1');
select throws_ok($q$select pg_temp.cstart(21,'ADMITTED',1,null,202)$q$,'P0001','SOURCE_ATTEMPT_CONFLICT','duplicate phase CAS rejects');
select is(pg_temp.cobserve(21,'IO_ACTIVE',1,201,'UNKNOWN')->>'phase','IO_UNKNOWN','timeout becomes UNKNOWN');
select throws_ok($q$select pg_temp.cstart(21,'IO_UNKNOWN',1,201,202)$q$,'P0001','SOURCE_ATTEMPT_CONFLICT','UNKNOWN cannot restart by timeout');
select throws_ok($q$select pg_temp.cfinal(21,1,201)$q$,'P0001','SOURCE_ATTEMPT_CONFLICT','UNKNOWN cannot finalize or release');
select throws_ok($q$select pg_temp.cobserve(21,'IO_UNKNOWN',2,201,'DEFINITIVE_COMPLETION')$q$,'P0001','SOURCE_ATTEMPT_CONFLICT','stale generation completion rejects');
select is(pg_temp.cobserve(21,'IO_UNKNOWN',1,201,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','explicit exact completion establishes quiescence');
select is(pg_temp.cstart(21,'IO_QUIESCENT',1,201,202)->>'attempt_generation','2','retry allocates new attempt and increments once');
select throws_ok($q$select pg_temp.cobserve(21,'IO_ACTIVE',1,201,'DEFINITIVE_COMPLETION')$q$,'P0001','SOURCE_ATTEMPT_CONFLICT','old attempt cannot finish new generation');
select is(pg_temp.cobserve(21,'IO_ACTIVE',2,202,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','new owner exact completion');
insert into ci3d_results values(22,pg_temp.cfinal(21,2,202));
select is((select value->>'outcome' from ci3d_results where n=22),'APPLIED','trusted proof verifies once');
select is((select row_revision::int from public.trip_source_representations where id=pg_temp.cid(101)),2,'VERIFY increments Representation once');
select is((select row_revision::int from public.trip_sources where id=pg_temp.cid(100)),1,'child mutation does not increment Source');
select throws_ok($q$update public.trip_source_operations set phase=phase where id=pg_temp.cid(21)$q$,'42501','SOURCE_OPERATION_IMMUTABLE','FINAL write-once receipt');
reset role;
select is(pg_temp.clook(21),(select value from ci3d_results where n=22),'VERIFY exact response-loss lookup');
reset session authorization; set local role postgres;
insert into ci3d_inputs values(30,pg_temp.cinput('MARK_REPRESENTATION_LOST',30,100,101,1,2)),(31,pg_temp.cinput('VERIFY_REPRESENTATION',31,100,101,1,1));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('VERIFY_REPRESENTATION',31)->>'error_code','REPRESENTATION_CAS_CONFLICT','stale representation CAS terminal rejection');
select is(pg_temp.ccall('MARK_REPRESENTATION_LOST',30)->>'phase','ADMITTED','MARK_LOST admission requires VERIFIED');
set role otr_trip_source_writer;
select is(pg_temp.cstart(30,'ADMITTED',1,null,301)->>'phase','IO_ACTIVE','loss probe ownership');
select is(pg_temp.cobserve(30,'IO_ACTIVE',1,301,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','definite loss probe completed');
select is(pg_temp.cfinal(30,1,301,'DEFINITE_MISSING')->>'result_remote_state','LOST','definitive missing proof marks LOST');
select ok((select verified_at is not null from public.trip_source_representations where id=pg_temp.cid(101)),'LOST preserves historical verification time');
reset role;
select is(pg_temp.clook(21),(select value from ci3d_results where n=22),'historic verified result stays historic after LOST');
reset session authorization; set local role postgres;
insert into ci3d_inputs values(40,pg_temp.cinput('RECOVER_REPRESENTATION',40,100,101,1,3)),(41,pg_temp.cinput('RECOVER_REPRESENTATION',41,100,101,1,3));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('RECOVER_REPRESENTATION',40)->>'phase','ADMITTED','LOST exact recovery admitted');
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',41)$q$,'23505',null,'exclusive admitted write slot blocks overlap');
set role otr_trip_source_writer;
select is(pg_temp.cstart(40,'ADMITTED',1,null,401)->>'phase','IO_ACTIVE','recovery first owned attempt');
select is(pg_temp.cobserve(40,'IO_ACTIVE',1,401,'UNKNOWN')->>'phase','IO_UNKNOWN','unknown recovery retains slot');
reset role;
select throws_ok($q$select pg_temp.ccall('RECOVER_REPRESENTATION',41)$q$,'23505',null,'unknown timeout never releases live write slot');
set role otr_trip_source_writer;
select is(pg_temp.cobserve(40,'IO_UNKNOWN',1,401,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','recovery explicit quiescence');
select is(pg_temp.cfinal(40,1,401)->>'result_remote_state','VERIFIED','identical-byte recovery verifies exact original');
select is((select current_material_revision::int from public.trip_sources where id=pg_temp.cid(100)),1,'recovery creates no material revision');
reset role;
reset session authorization; set local role postgres;
insert into ci3d_inputs values(50,pg_temp.cinput('REPLACE_MATERIAL',50,100,151,1,1,1,'BINARY','new exact material')),(51,pg_temp.cinput('REPLACE_MATERIAL',51,100,152,1,1,1));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('REPLACE_MATERIAL',50)->>'result_material_revision','2','replacement append rev2');
select is(pg_temp.ccall('REPLACE_MATERIAL',51)->>'error_code','SOURCE_CAS_CONFLICT','stale Source CAS rejects no dangling descriptor');
reset session authorization; set local role postgres;
select is((select row_revision::int from public.trip_sources where id=pg_temp.cid(100)),2,'REPLACE increments Source exactly once');
select is((select count(*)::int from public.trip_source_revisions where source_id=pg_temp.cid(100)),2,'old revision retained');
select is((select row_revision::int from public.trip_source_representations where id=pg_temp.cid(101)),4,'old original preserved through replacement');
select ok(not exists(select 1 from public.trip_source_representations where id=pg_temp.cid(152)),'stale replacement inserts no new descriptor');
set constraints all immediate; set constraints all deferred;
create function pg_temp.fail_operation() returns trigger language plpgsql as $$ begin raise exception 'fixture receipt failure'; end $$;
create trigger ci3d_fail before insert on public.trip_source_operations for each row execute function pg_temp.fail_operation();
insert into ci3d_inputs values(55,pg_temp.cinput('ACQUIRE_SOURCE',55,550,551));
reset role; set session authorization otr_trip_source_command_gateway;
select throws_ok($q$select pg_temp.ccall('ACQUIRE_SOURCE',55)$q$,'P0001','fixture receipt failure','receipt failure aborts full acquisition');
reset session authorization; set local role postgres;
select ok(not exists(select 1 from public.trip_sources where id=pg_temp.cid(550)) and not exists(select 1 from public.trip_source_representations where id=pg_temp.cid(551)),'receipt failure leaves no orphan metadata');
drop trigger ci3d_fail on public.trip_source_operations;
reset role; grant execute on function public.trip_source_admission(uuid,uuid,boolean) to postgres; set local role postgres;
-- Downgrade owner admission to current read-only guest while retaining private ownership.
insert into public.trips(id,name,created_by) values(pg_temp.cid(900),'Read-only test','00000000-0000-4000-8000-000000000002');
insert into public.journey_members(id,trip_id,user_id,display_name,role,status,linked_at) values(pg_temp.cid(901),pg_temp.cid(900),'00000000-0000-4000-8000-000000000001','Synthetic owner','group_member','linked',now());
insert into ci3d_inputs values(70,pg_temp.cinput('ACQUIRE_SOURCE',70,910,911,1,1,1,'BINARY','private',pg_temp.cid(900))),
 (71,pg_temp.cinput('VERIFY_REPRESENTATION',71,910,911,1,1,1,'BINARY','private',pg_temp.cid(900))),
 (72,pg_temp.cinput('PREPARE_REPRESENTATION',72,910,911,1,1,1,'BINARY','private',pg_temp.cid(900)));
reset role; set session authorization otr_trip_source_command_gateway;
insert into ci3d_results values(70,pg_temp.ccall('ACQUIRE_SOURCE',70));
select is(pg_temp.ccall('VERIFY_REPRESENTATION',71)->>'phase','ADMITTED','owner admitted in exact second Trip');
set role otr_trip_source_writer;
select is(pg_temp.cstart(71,'ADMITTED',1,null,701)->>'phase','IO_ACTIVE','current writer starts before revocation');
select is(pg_temp.cobserve(71,'IO_ACTIVE',1,701,'UNKNOWN')->>'phase','IO_UNKNOWN','revocation fixture unknown I/O');
reset role; reset session authorization; set local role postgres;
update public.journey_members set role='guest' where id=pg_temp.cid(901);
select ok(public.trip_source_admission('00000000-0000-4000-8000-000000000001',pg_temp.cid(900),false) and not public.trip_source_admission('00000000-0000-4000-8000-000000000001',pg_temp.cid(900),true),'current owner is read-only guest');
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.clook(70),(select value from ci3d_results where n=70),'historic receipt survives loss of write admission');
select is(pg_temp.clook(71)->>'phase','IO_UNKNOWN','historic UNKNOWN lookup needs read only');
select is(pg_temp.ccall('VERIFY_REPRESENTATION',71)->>'phase','IO_UNKNOWN','read-only exact replay does not dispatch');
select throws_ok($q$select pg_temp.ccall('PREPARE_REPRESENTATION',72)$q$,'42501','SOURCE_ACCESS_DENIED','new PREPARE read-only denied');
set role otr_trip_source_writer;
select is(pg_temp.cobserve(71,'IO_UNKNOWN',1,701,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','trusted completion records quiescence after write revocation');
select throws_ok($q$select pg_temp.cfinal(71,1,701)$q$,'42501','SOURCE_ACCESS_DENIED','semantic finalization requires current write admission');
select throws_ok($q$select pg_temp.cstart(71,'IO_QUIESCENT',1,701,702)$q$,'42501','SOURCE_ACCESS_DENIED','resume requires current write admission');
reset role; reset session authorization; set local role postgres;
update public.journey_members set status='unlinked',user_id=null where id=pg_temp.cid(901);
reset role; set session authorization otr_trip_source_command_gateway;
select throws_ok($q$select pg_temp.clook(70)$q$,'42501','SOURCE_ACCESS_DENIED','loss of read admission denies historic private receipt');
select ok(public.trip_source_operation_lookup('00000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001',pg_temp.cid(100),pg_temp.cid(10),'op-10',(select raw::jsonb->>'operation_sha256' from ci3d_inputs where n=10)) is null,'foreign owner cannot enumerate guessed operation');
reset role; reset session authorization; set local role postgres;
insert into ci3d_inputs values(60,pg_temp.cinput('VERIFY_REPRESENTATION',60,100,151,2,1,2));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('VERIFY_REPRESENTATION',60)->>'phase','ADMITTED','late proof admitted at source base2');
set role otr_trip_source_writer;
select is(pg_temp.cstart(60,'ADMITTED',1,null,601)->>'phase','IO_ACTIVE','late proof attempt started');
select is(pg_temp.cobserve(60,'IO_ACTIVE',1,601,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','late proof quiescent');
reset role; reset session authorization; set local role postgres;
-- Trusted concurrent semantic change makes original proof stale, never refresh its pins.
update public.trip_sources set row_revision=row_revision+1 where id=pg_temp.cid(100);
reset role; set session authorization otr_trip_source_command_gateway; set role otr_trip_source_writer;
select is(pg_temp.cfinal(60,1,601)->>'error_code','SOURCE_CAS_CONFLICT','late proof cannot adopt newer Source base');
select is((select remote_state from public.trip_source_representations where id=pg_temp.cid(151)),'PENDING','late proof leaves newer material unchanged');
reset role; reset session authorization; set local role postgres;
insert into ci3d_inputs values(80,pg_temp.cinput('VERIFY_REPRESENTATION',80,100,151,3,1,2));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('VERIFY_REPRESENTATION',80)->>'phase','ADMITTED','late RETAINED/LOST proof admitted before change');
set role otr_trip_source_writer;
select is(pg_temp.cstart(80,'ADMITTED',1,null,801)->>'phase','IO_ACTIVE','late LOST proof owned');
select is(pg_temp.cobserve(80,'IO_ACTIVE',1,801,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','late LOST proof quiescent');
reset role; reset session authorization; set local role postgres;
update public.trip_source_representations set remote_state='LOST',retention_state='RETAINED',row_revision=2 where id=pg_temp.cid(151);
reset role; set session authorization otr_trip_source_command_gateway; set role otr_trip_source_writer;
select is(pg_temp.cfinal(80,1,801)->>'error_code','REPRESENTATION_CAS_CONFLICT','late proof cannot resurrect newer RETAINED/LOST');
select is((select remote_state||'/'||retention_state from public.trip_source_representations where id=pg_temp.cid(151)),'LOST/RETAINED','late proof preserves RETAINED/LOST');
reset role; reset session authorization; set local role postgres;
update public.trip_source_representations set remote_state='PENDING',retention_state='RETAINED',row_revision=3 where id=pg_temp.cid(151);
insert into ci3d_inputs values(81,pg_temp.cinput('VERIFY_REPRESENTATION',81,100,151,3,3,2));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('VERIFY_REPRESENTATION',81)->>'phase','ADMITTED','late PAYLOAD_PURGED/PURGED proof admitted before change');
set role otr_trip_source_writer;
select is(pg_temp.cstart(81,'ADMITTED',1,null,811)->>'phase','IO_ACTIVE','late PURGED proof owned');
select is(pg_temp.cobserve(81,'IO_ACTIVE',1,811,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','late PURGED proof quiescent');
reset role; reset session authorization; set local role postgres;
update public.trip_source_representations set remote_state='PURGED',retention_state='PAYLOAD_PURGED',row_revision=4 where id=pg_temp.cid(151);
reset role; set session authorization otr_trip_source_command_gateway; set role otr_trip_source_writer;
select is(pg_temp.cfinal(81,1,811)->>'error_code','REPRESENTATION_CAS_CONFLICT','late proof cannot resurrect newer PAYLOAD_PURGED/PURGED');
select is((select remote_state||'/'||retention_state from public.trip_source_representations where id=pg_temp.cid(151)),'PURGED/PAYLOAD_PURGED','late proof preserves PAYLOAD_PURGED/PURGED');
reset role; reset session authorization; set local role postgres;
update public.trip_source_representations set remote_state='PENDING',retention_state='RETAINED',row_revision=5 where id=pg_temp.cid(151);
insert into ci3d_inputs values(82,pg_temp.cinput('VERIFY_REPRESENTATION',82,100,151,3,5,2));
reset role; set session authorization otr_trip_source_command_gateway;
select is(pg_temp.ccall('VERIFY_REPRESENTATION',82)->>'phase','ADMITTED','late IDENTITY_ONLY/PURGED proof admitted before change');
set role otr_trip_source_writer;
select is(pg_temp.cstart(82,'ADMITTED',1,null,821)->>'phase','IO_ACTIVE','late PURGED proof owned');
select is(pg_temp.cobserve(82,'IO_ACTIVE',1,821,'DEFINITIVE_COMPLETION')->>'phase','IO_QUIESCENT','late PURGED proof quiescent');
reset role; reset session authorization; set local role postgres;
update public.trip_source_representations set remote_state='PURGED',retention_state='IDENTITY_ONLY',row_revision=6,payload_sha256=null,byte_count=null where id=pg_temp.cid(151);
reset role; set session authorization otr_trip_source_command_gateway; set role otr_trip_source_writer;
select is(pg_temp.cfinal(82,1,821)->>'error_code','REPRESENTATION_CAS_CONFLICT','late proof cannot resurrect newer IDENTITY_ONLY/PURGED');
select is((select remote_state||'/'||retention_state from public.trip_source_representations where id=pg_temp.cid(151)),'PURGED/IDENTITY_ONLY','late proof preserves IDENTITY_ONLY/PURGED');
reset role; reset session authorization; set local role postgres;
set timezone='UTC';
select is((select value from ci3d_before),jsonb_build_object(
 'a',(select jsonb_agg(to_jsonb(x) order by id) from public.journey_members x where trip_id<>pg_temp.cid(900)),
 'b',(select jsonb_agg(to_jsonb(x) order by id) from public.itinerary_events x),
 'br',(select jsonb_agg(to_jsonb(x) order by trip_id,actor_account_id,operation_key) from public.trip_event_operation_receipts x),
 'expense',(select jsonb_agg(to_jsonb(x) order by id) from public.expenses x),
 'receipt',(select jsonb_agg(to_jsonb(x) order by id) from public.receipt_assets x),
 'payment',(select jsonb_agg(to_jsonb(x) order by id) from public.personal_settlement_payment_records x),
 'buckets',(select jsonb_agg(to_jsonb(x) order by id) from storage.buckets x)),'A/B/receipt/financial/bucket populated facts unchanged');
select * from finish();
rollback;
