-- Synthetic no-provider canonical admission fixture; never product activation.
\connect postgres supabase_admin
begin;
set local role postgres;
set search_path=public,extensions;
create temporary table ci3d_inputs(n integer primary key,raw text);
create temporary table ci3d_results(n integer primary key,value jsonb);
grant select,insert,update on ci3d_inputs,ci3d_results to public;
create function pg_temp.cid(n integer) returns uuid language sql immutable as $$ select ('cd000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid $$;
create function pg_temp.cinput(family text,n integer,sid integer,rid integer,sbase bigint default 1,rbase bigint default 1,mat bigint default 1,kind text default 'BINARY',content text default 'synthetic',target_trip uuid default '10000000-0000-4000-8000-000000000001') returns text
language plpgsql security definer set search_path=pg_catalog as $$ declare j jsonb; p jsonb; d jsonb; cap jsonb; input jsonb; h text; prev bigint; rev bigint;
begin
 d:=jsonb_build_object('id',pg_temp.cid(rid),'material_kind',kind,'original_filename',case when kind='BINARY' then 'synthetic.png' end,'part_key',null,'mime_type',case when kind='BINARY' then 'image/png' end,'encoding',case when kind<>'BINARY' then 'UTF-8' end,'payload_sha256',encode(extensions.digest(content,'sha256'),'hex'),'byte_count',octet_length(content),'text_content',case when kind='TEXT' then content end,'locator_uri',case when kind='LOCATOR' then content end);
 input:=jsonb_build_object('source_kind',case kind when 'BINARY' then 'IMAGE' when 'TEXT' then 'TEXT' else 'URL' end,'acquisition_channel',case kind when 'BINARY' then 'FILES' when 'TEXT' then 'PASTE' else 'URL_CAPTURE' end,'captured_at',null,'capture_time_basis','UNKNOWN');
 rev:=case when family='ACQUIRE_SOURCE' then 1 else mat+1 end; prev:=case when family='REPLACE_MATERIAL' then mat end;
 cap:=jsonb_build_object('completeness','AS_SUPPLIED','capture_sha256',public.trip_source_hash('otr-source-capture-v1',jsonb_build_array(1,pg_temp.cid(sid),rev,prev,jsonb_build_array(pg_temp.cid(rid)),'AS_SUPPLIED',case when family='ACQUIRE_SOURCE' then 'ACQUISITION' else 'REPLACEMENT' end,null,null)));
 p:=jsonb_build_object('material_revision',mat,'expected_source_row_revision',sbase,'expected_source_state',jsonb_build_object('lifecycle','ACTIVE','retention_state','RETAINED'),'representation_id',pg_temp.cid(rid),'expected_representation_row_revision',rbase,'expected_representation_state',jsonb_build_object('remote_state',case family when 'MARK_REPRESENTATION_LOST' then 'VERIFIED' when 'RECOVER_REPRESENTATION' then 'LOST' else 'PENDING' end,'retention_state','RETAINED'));
 if family='ACQUIRE_SOURCE' then
  p:=jsonb_build_object('acquisition_key','op-'||n,'acquisition_sha256',public.trip_source_hash('otr-source-acquisition-v1',jsonb_build_array(1,target_trip,'00000000-0000-4000-8000-000000000001',pg_temp.cid(sid),'op-'||n,input->'source_kind',input->'acquisition_channel',null,'UNKNOWN',cap->'capture_sha256',jsonb_build_array(d->'id',d->'material_kind',d->'original_filename',d->'part_key',d->'mime_type',d->'encoding',d->'payload_sha256',d->'byte_count',d->'text_content',d->'locator_uri'))),'source_input',input,'capture',cap,'original',d);
 elsif family='REPLACE_MATERIAL' then
  p:=(p-array['representation_id','expected_representation_row_revision','expected_representation_state'])||jsonb_build_object('expected_current_material_revision',mat,'capture',cap,'original',d);
 end if;
 if family='UPLOAD_ORIGINAL' then p:=p||jsonb_build_object('parent_operation_id',pg_temp.cid(case when sid=110 then 30 else 20 end),'payload_sha256',d->'payload_sha256','byte_count',d->'byte_count','mime_type',d->'mime_type'); end if;
 j:=jsonb_build_object('contract_version',1,'command',family,'operation_id',pg_temp.cid(n),'operation_key','op-'||n,'actor_account_id','00000000-0000-4000-8000-000000000001','trip_id',target_trip,'source_id',pg_temp.cid(sid),'payload',p);
 if family='UPLOAD_ORIGINAL' then h:=public.trip_source_hash('otr-source-upload-v1',jsonb_build_array(1,j->'operation_id',j->'operation_key',j->'actor_account_id',j->'trip_id',j->'source_id')||public.trip_source_payload_tuple(family,p)); else
 h:=public.trip_source_hash('otr-source-command-v1',jsonb_build_array(1,family,j->'operation_id',j->'operation_key',j->'actor_account_id',j->'trip_id',j->'source_id',public.trip_source_payload_tuple(family,p)));
 end if;
 return (j||jsonb_build_object('operation_sha256',h))::text;
end $$;
create function pg_temp.ccall(family text,n integer) returns jsonb language plpgsql as $$ declare raw text; actor uuid:='00000000-0000-4000-8000-000000000001'; begin
 select i.raw into strict raw from ci3d_inputs i where i.n=ccall.n;
 case family
 when 'ACQUIRE_SOURCE' then return public.trip_source_acquire_source(actor,raw);
 when 'PREPARE_REPRESENTATION' then return public.trip_source_prepare_representation(actor,raw);
 when 'REPLACE_MATERIAL' then return public.trip_source_replace_material(actor,raw);
 when 'VERIFY_REPRESENTATION' then return public.trip_source_verify_representation(actor,raw);
 when 'MARK_REPRESENTATION_LOST' then return public.trip_source_mark_representation_lost(actor,raw);
 when 'RECOVER_REPRESENTATION' then return public.trip_source_recover_representation(actor,raw);
 when 'UPLOAD_ORIGINAL' then return public.trip_source_upload_original(actor,raw);
 end case; end $$;
create function pg_temp.clook(n integer) returns jsonb language sql as $$ select public.trip_source_operation_lookup('00000000-0000-4000-8000-000000000001',(raw::jsonb->>'trip_id')::uuid,(raw::jsonb->>'source_id')::uuid,pg_temp.cid(n),raw::jsonb->>'operation_key',raw::jsonb->>'operation_sha256') from ci3d_inputs where ci3d_inputs.n=clook.n $$;
create function pg_temp.cstart(n integer,phase text,generation bigint,prior integer,attempt integer) returns jsonb language sql as $$ select public.trip_source_attempt_start('00000000-0000-4000-8000-000000000001',(raw::jsonb->>'trip_id')::uuid,(raw::jsonb->>'source_id')::uuid,pg_temp.cid(n),raw::jsonb->>'operation_key',raw::jsonb->>'operation_sha256',phase,generation,case when prior is not null then pg_temp.cid(prior) end,pg_temp.cid(attempt)) from ci3d_inputs where ci3d_inputs.n=cstart.n $$;
create function pg_temp.cobserve(n integer,phase text,generation bigint,attempt integer,observation text) returns jsonb language sql as $$ select public.trip_source_attempt_observe(pg_temp.cid(n),raw::jsonb->>'operation_sha256',phase,generation,pg_temp.cid(attempt),observation) from ci3d_inputs where ci3d_inputs.n=cobserve.n $$;
create function pg_temp.cfinal(n integer,generation bigint,attempt integer,kind text default 'MATCH') returns jsonb language sql as $$ select public.trip_source_finalize(o.actor_account_id,o.trip_id,o.source_id,o.id,o.operation_key,o.operation_sha256,generation,pg_temp.cid(attempt),jsonb_build_object('operation_id',o.id,'attempt_id',pg_temp.cid(attempt),'attempt_generation',generation,'kind',kind,'payload_sha256',case when kind<>'DEFINITE_MISSING' then o.bound_payload_sha256 end,'byte_count',case when kind<>'DEFINITE_MISSING' then o.bound_byte_count end,'mime_type',case when kind<>'DEFINITE_MISSING' then o.bound_mime_type end,'observed_at',public.trip_event_utc_timestamp(o.io_finished_at))) from public.trip_source_operations o where o.id=pg_temp.cid(n) $$;
-- Trusted opening is rolled back; runtime migration has no setter/DML grant.
alter table public.trip_source_command_gate drop constraint trip_source_gate_closed;
update public.trip_source_command_gate set enabled=true;
grant select,insert,update on public.trip_sources,public.trip_source_revisions,public.trip_source_representations,public.trip_source_actions,public.trip_source_operations to otr_trip_source_writer;
grant select,update on public.trips,public.trip_members,public.journey_members to otr_trip_source_writer;
grant execute on function public.trip_source_uuid_array_valid(uuid[],integer,integer) to otr_trip_source_writer;
alter table public.trip_sources disable trigger trip_source_mutation_guard;
alter table public.trip_sources disable trigger trip_source_statement_guard;
alter table public.trip_source_revisions disable trigger trip_source_mutation_guard;
alter table public.trip_source_revisions disable trigger trip_source_statement_guard;
alter table public.trip_source_representations disable trigger trip_source_mutation_guard;
alter table public.trip_source_representations disable trigger trip_source_statement_guard;
alter table public.trip_source_actions disable trigger trip_source_mutation_guard;
alter table public.trip_source_actions disable trigger trip_source_statement_guard;
create policy ci3d_fixture on public.trip_sources for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_revisions for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_representations for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_actions for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_source_operations for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trips for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.trip_members for all to otr_trip_source_writer using(true) with check(true);
create policy ci3d_fixture on public.journey_members for all to otr_trip_source_writer using(true) with check(true);
grant otr_trip_source_writer to otr_trip_source_command_gateway with inherit false,set true;

insert into ci3d_inputs values(10,pg_temp.cinput('ACQUIRE_SOURCE',10,100,101)),(11,pg_temp.cinput('ACQUIRE_SOURCE',11,110,111));
reset role;set session authorization otr_trip_source_command_gateway;
select pg_temp.ccall('ACQUIRE_SOURCE',10),pg_temp.ccall('ACQUIRE_SOURCE',11);
reset session authorization;set local role postgres;
insert into ci3d_inputs values(20,pg_temp.cinput('PREPARE_REPRESENTATION',20,100,101)),(30,pg_temp.cinput('PREPARE_REPRESENTATION',30,110,111));
reset role;set session authorization otr_trip_source_command_gateway;
select pg_temp.ccall('PREPARE_REPRESENTATION',20),pg_temp.ccall('PREPARE_REPRESENTATION',30);
reset session authorization;set local role postgres;
insert into ci3d_inputs values(23,pg_temp.cinput('UPLOAD_ORIGINAL',23,100,101)),(33,pg_temp.cinput('UPLOAD_ORIGINAL',33,110,111));
reset role;set session authorization otr_trip_source_command_gateway;
select pg_temp.ccall('UPLOAD_ORIGINAL',23),pg_temp.ccall('UPLOAD_ORIGINAL',33);
set local role otr_trip_source_writer;
select pg_temp.cstart(23,'ADMITTED',1,null,231),pg_temp.cstart(33,'ADMITTED',1,null,331);
select pg_temp.cobserve(33,'IO_ACTIVE',1,331,'UNKNOWN');
reset session authorization;set local role postgres;

set constraints all immediate;
update public.trip_source_command_gate set enabled=false;
alter table public.trip_source_command_gate add constraint trip_source_gate_closed check(not enabled);
revoke otr_trip_source_writer from otr_trip_source_command_gateway;
alter table public.trip_sources enable trigger trip_source_mutation_guard;alter table public.trip_sources enable trigger trip_source_statement_guard;
drop policy ci3d_fixture on public.trip_sources;
revoke select,insert,update on public.trip_sources from otr_trip_source_writer;
alter table public.trip_source_revisions enable trigger trip_source_mutation_guard;alter table public.trip_source_revisions enable trigger trip_source_statement_guard;
drop policy ci3d_fixture on public.trip_source_revisions;
revoke select,insert,update on public.trip_source_revisions from otr_trip_source_writer;
alter table public.trip_source_representations enable trigger trip_source_mutation_guard;alter table public.trip_source_representations enable trigger trip_source_statement_guard;
drop policy ci3d_fixture on public.trip_source_representations;
revoke select,insert,update on public.trip_source_representations from otr_trip_source_writer;
alter table public.trip_source_actions enable trigger trip_source_mutation_guard;alter table public.trip_source_actions enable trigger trip_source_statement_guard;
drop policy ci3d_fixture on public.trip_source_actions;
revoke select,insert,update on public.trip_source_actions from otr_trip_source_writer;
drop policy ci3d_fixture on public.trip_source_operations;
revoke select,insert,update on public.trip_source_operations from otr_trip_source_writer;
drop policy ci3d_fixture on public.trips;
revoke select,insert,update on public.trips from otr_trip_source_writer;
drop policy ci3d_fixture on public.trip_members;
revoke select,insert,update on public.trip_members from otr_trip_source_writer;
drop policy ci3d_fixture on public.journey_members;
revoke select,insert,update on public.journey_members from otr_trip_source_writer;
revoke execute on function public.trip_source_uuid_array_valid(uuid[],integer,integer) from otr_trip_source_writer;
set constraints all immediate;
create extension if not exists pgtap with schema extensions;
select no_plan();
select is((select enabled from public.trip_source_command_gate),false,'canonical gate restored CLOSED before journal tests');
create function pg_temp.jreg(n integer,op integer,token integer) returns jsonb language sql as $$
 select public.trip_source_execution_register(pg_temp.cid(op),pg_temp.cid(n),1,pg_temp.cid(500),pg_temp.cid(600),repeat('b',64),pg_temp.cid(token),'PNG_STATIC_RGB8_RGBA8_V1','526b66b7bd63daeed309c3d2630cdeaec759a6031a9efe7ade381c06fd04ede5') $$;
create function pg_temp.jclaim(n integer,f bigint,owner integer) returns jsonb language sql as $$ select public.trip_source_execution_claim(pg_temp.cid(n),f,pg_temp.cid(owner)) $$;
create function pg_temp.jattach(n integer,f bigint,owner integer,token integer,c text default repeat('a',64)) returns jsonb language sql as $$ select public.trip_source_execution_attach(pg_temp.cid(n),pg_temp.cid(owner),f,pg_temp.cid(600),pg_temp.cid(token),c) $$;
create function pg_temp.jphase(n integer,f bigint,owner integer,p text) returns jsonb language sql as $$ select public.trip_source_execution_advance(pg_temp.cid(n),pg_temp.cid(owner),f,p) $$;
create function pg_temp.jterminal(n integer,f bigint,owner integer,token integer,c text default repeat('a',64)) returns jsonb language sql as $$ select public.trip_source_execution_terminal(pg_temp.cid(n),pg_temp.cid(owner),f,pg_temp.cid(600),pg_temp.cid(token),c,clock_timestamp(),repeat('d',64),'PARSER_TIMEOUT') $$;
create function pg_temp.jrelease(n integer,f bigint,owner integer) returns jsonb language sql as $$ select public.trip_source_execution_release(pg_temp.cid(n),pg_temp.cid(owner),f) $$;
reset role;grant usage on schema extensions to otr_trip_source_execution_gateway,otr_trip_source_execution_writer;grant otr_trip_source_execution_gateway to otr_trip_source_command_gateway with inherit false,set true;
reset role;set session authorization otr_trip_source_command_gateway;set local role otr_trip_source_execution_gateway;
select throws_ok($q$select pg_temp.jreg(999,23,701)$q$,'P0001','SOURCE_EXECUTION_OPERATION_CONFLICT','registration rejects changed exact attempt');
select throws_ok($q$select pg_temp.jreg(231,999,701)$q$,'P0001','SOURCE_EXECUTION_OPERATION_CONFLICT','registration rejects unknown operation');
select throws_ok($q$select public.trip_source_execution_register(pg_temp.cid(23),pg_temp.cid(231),2,pg_temp.cid(500),pg_temp.cid(600),repeat('b',64),pg_temp.cid(701),'PNG_STATIC_RGB8_RGBA8_V1','526b66b7bd63daeed309c3d2630cdeaec759a6031a9efe7ade381c06fd04ede5')$q$,'P0001','SOURCE_EXECUTION_OPERATION_CONFLICT','registration rejects changed canonical generation');
select is(pg_temp.jreg(231,23,701)->>'phase','STARTING','durable registration before staging');
select is(pg_temp.jreg(331,33,702)->>'phase','UNKNOWN','same byte resource has second protected reference');
select throws_ok($q$select pg_temp.jreg(231,23,701)$q$,'23505',null,'duplicate exact admission cannot allocate parallel attempt');
select is(jsonb_array_length(public.trip_source_execution_inventory()),2,'inventory contains STARTING/UNKNOWN without runtime identity');
select ok((public.trip_source_execution_inventory()->0) ? 'staged_resource','inventory includes exact durable node/key/hash/count');
select is(pg_temp.jclaim(231,0,901)->>'owner_fence','1','first claim fence 0 to 1');
select throws_ok($q$select pg_temp.jclaim(231,0,902)$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','duplicate claim fails');
select throws_ok($q$select pg_temp.jterminal(231,1,901,701)$q$,'P0001','SOURCE_EXECUTION_PROOF_CONFLICT','missing exact runtime identity cannot prove terminality');
select throws_ok($q$select pg_temp.jrelease(231,1,901)$q$,'P0001','SOURCE_STAGE_PROTECTED','STARTING blocks cleanup');
select throws_ok($q$select pg_temp.jattach(231,1,901,999)$q$,'P0001','SOURCE_EXECUTION_IDENTITY_CONFLICT','unrelated run token rejected');
select is(pg_temp.jattach(231,1,901,701)->>'container_id',repeat('a',64),'exact runtime identity attaches once');
select throws_ok($q$select pg_temp.jattach(231,1,901,701,repeat('e',64))$q$,'P0001','SOURCE_EXECUTION_IDENTITY_CONFLICT','known runtime identity immutable');
select is(pg_temp.jphase(231,1,901,'RUNNING')->>'phase','RUNNING','exact owned STARTING to RUNNING');
select is(public.trip_source_execution_inventory()->0->>'phase','RUNNING','RUNNING retained in recovery inventory');
savepoint owner_rollback;
select is(pg_temp.jclaim(231,1,902)->>'owner_fence','2','takeover advances fence');
rollback to owner_rollback;
select is(public.trip_source_execution_inventory()->0->>'owner_fence','1','rollback preserves prior owner fence');
select is(pg_temp.jphase(231,1,901,'TERMINATION_REQUIRED')->>'phase','TERMINATION_REQUIRED','durable termination responsibility before UNKNOWN');
select is(public.trip_source_execution_inventory()->0->>'termination_outstanding','true','obligation is durable');
select is(pg_temp.jclaim(231,1,902)->>'phase','UNKNOWN','takeover cannot redispatch');
select throws_ok($q$select pg_temp.jphase(231,1,901,'RUNNING')$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','stale old owner cannot advance');
select throws_ok($q$select pg_temp.jterminal(231,1,901,701)$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','stale terminal observation rejected');
select throws_ok($q$select pg_temp.jattach(231,1,901,701)$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','stale identity cannot replace');
select throws_ok($q$select pg_temp.jrelease(231,1,901)$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','stale owner cannot clear reference');
select throws_ok($q$select pg_temp.jphase(231,2,902,'RUNNING')$q$,'P0001','SOURCE_EXECUTION_PHASE_CONFLICT','UNKNOWN takeover grants no new dispatch');
select throws_ok($q$select pg_temp.jrelease(231,2,902)$q$,'P0001','SOURCE_STAGE_PROTECTED','UNKNOWN cannot authorize cleanup');
select is(pg_temp.jclaim(231,2,901)->>'owner_fence','3','A to B to A still advances fence');
select throws_ok($q$select pg_temp.jphase(231,1,901,'UNKNOWN')$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','returning owner UUID does not restore stale A authority');
select throws_ok($q$select pg_temp.jterminal(231,3,901,701,repeat('e',64))$q$,'P0001','SOURCE_EXECUTION_PROOF_CONFLICT','unrelated container cannot be targeted by terminal evidence');
select is(pg_temp.jterminal(231,3,901,701)->>'phase','TERMINAL','synthetic trusted exact observation seals local terminal result');
select is(jsonb_array_length(public.trip_source_execution_inventory()),2,'terminal cleanup-pending remains in recovery inventory');
savepoint cleanup_takeover;
select is(pg_temp.jclaim(231,3,902)->>'phase','TERMINAL','cleanup-pending takeover retains terminal phase and proof');
select is(public.trip_source_execution_inventory()->0->>'owner_fence','4','cleanup responsibility takeover increments fence');
select throws_ok($q$select pg_temp.jrelease(231,3,901)$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','old terminal owner cannot release after cleanup takeover');
select throws_ok($q$select pg_temp.jphase(231,4,902,'RUNNING')$q$,'P0001','SOURCE_EXECUTION_PHASE_CONFLICT','new cleanup owner cannot reopen execution');
rollback to cleanup_takeover;
select throws_ok($q$select pg_temp.jphase(231,3,901,'RUNNING')$q$,'P0001','SOURCE_EXECUTION_PHASE_CONFLICT','terminal cannot reopen by current owner');
select throws_ok($q$select pg_temp.jrelease(231,3,901)$q$,'P0001','SOURCE_STAGE_PROTECTED','other unresolved reference blocks terminal attempt cleanup');
select is(pg_temp.jclaim(331,0,902)->>'owner_fence','1','second reference claims independently');
select is(pg_temp.jphase(331,1,902,'UNKNOWN')->>'phase','UNKNOWN','missing runtime remains UNKNOWN');
select throws_ok($q$select pg_temp.jterminal(331,1,902,702,repeat('b',64))$q$,'P0001','SOURCE_EXECUTION_PROOF_CONFLICT','missing identity after crash remains protected');
select throws_ok($q$select pg_temp.jattach(331,1,902,702)$q$,'23505',null,'same exact node/container cannot bind to unrelated attempt');
select is(pg_temp.jattach(331,1,902,702,repeat('b',64))->>'container_id',repeat('b',64),'trusted recovery attaches exact previously unknown identity');
select is(pg_temp.jterminal(331,1,902,702,repeat('b',64))->>'phase','TERMINAL','second exact terminal observation');
select throws_ok($q$select public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(600),repeat('b',64),repeat('e',64))$q$,'P0001','SOURCE_STAGE_PROTECTED','terminal record alone cannot acknowledge unauthorized cleanup');
select throws_ok($q$select pg_temp.jrelease(231,3,901)$q$,'P0001','SOURCE_STAGE_PROTECTED','all parser proofs do not release canonical IO_ACTIVE/IO_UNKNOWN staging references');
reset session authorization;reset role;
select is((select phase from public.trip_source_operations where id=pg_temp.cid(23)),'IO_ACTIVE','parser terminality leaves provider IO_ACTIVE protected');
select is((select phase from public.trip_source_operations where id=pg_temp.cid(33)),'IO_UNKNOWN','parser terminality leaves provider IO_UNKNOWN protected');
-- Trusted fixture only: simulate separate definitive provider observations through
-- the accepted C-I3D helper. Opening and grants are rolled back, no product I/O.
set local role postgres;
alter table public.trip_source_command_gate drop constraint trip_source_gate_closed;
update public.trip_source_command_gate set enabled=true;
grant select,update on public.trip_source_operations to otr_trip_source_writer;
create policy ci3h_quiescence_fixture on public.trip_source_operations to otr_trip_source_writer using(true) with check(true);
reset role;grant otr_trip_source_writer to otr_trip_source_command_gateway with inherit false,set true;
set session authorization otr_trip_source_command_gateway;set local role otr_trip_source_writer;
select pg_temp.cobserve(23,'IO_ACTIVE',1,231,'DEFINITIVE_COMPLETION'),pg_temp.cobserve(33,'IO_UNKNOWN',1,331,'DEFINITIVE_COMPLETION');
reset session authorization;set local role postgres;
update public.trip_source_command_gate set enabled=false;
alter table public.trip_source_command_gate add constraint trip_source_gate_closed check(not enabled);
revoke select,update on public.trip_source_operations from otr_trip_source_writer;
drop policy ci3h_quiescence_fixture on public.trip_source_operations;
reset role;revoke otr_trip_source_writer from otr_trip_source_command_gateway;
set session authorization otr_trip_source_command_gateway;set local role otr_trip_source_execution_gateway;
select ok(pg_temp.jrelease(231,3,901)->>'release_authorized_at' is not null,'all attempts terminal permits durable release eligibility');
select is(jsonb_array_length(public.trip_source_execution_inventory()),2,'authorization alone retains durable cleanup-pending responsibility');
select throws_ok($q$select public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),1,pg_temp.cid(600),repeat('b',64),repeat('e',64))$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','stale generation cannot acknowledge cleanup');
select throws_ok($q$select public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(999),repeat('b',64),repeat('e',64))$q$,'P0001','SOURCE_STAGE_PROTECTED','wrong node cannot acknowledge cleanup');
select throws_ok($q$select public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(600),repeat('f',64),repeat('e',64))$q$,'P0001','SOURCE_STAGE_PROTECTED','wrong opaque key cannot acknowledge cleanup');
select lives_ok($q$select public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(600),repeat('b',64),repeat('e',64))$q$,'synthetic exact physical cleanup evidence recorded');
select throws_ok($q$select public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(600),repeat('b',64),repeat('f',64))$q$,'P0001','SOURCE_STAGE_PROOF_CONFLICT','cleanup evidence immutable');
select is(public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(600),repeat('b',64),repeat('e',64)),public.trip_source_execution_cleaned(pg_temp.cid(231),pg_temp.cid(901),3,pg_temp.cid(600),repeat('b',64),repeat('e',64)),'exact cleanup acknowledgement replay stable');
select throws_ok($q$select pg_temp.jclaim(231,3,902)$q$,'P0001','SOURCE_EXECUTION_FENCE_CONFLICT','cleaned responsibility cannot reopen or be claimed');
select is(public.trip_source_execution_inventory(),'[]'::jsonb,'positive cleanup evidence resolves inventory responsibility');
select is(pg_temp.jrelease(231,3,901),pg_temp.jrelease(231,3,901),'exact authorization replay does not reopen or lose cleanup responsibility');
reset session authorization;reset role;
select is((select phase from public.trip_source_operations where id=pg_temp.cid(23)),'IO_QUIESCENT','only separate trusted C-I3D observation established quiescence');
select is((select phase from public.trip_source_operations where id=pg_temp.cid(33)),'IO_QUIESCENT','journal cleanup does not change separately observed canonical phase');
select is((select enabled from public.trip_source_command_gate),false,'Source runtime remains closed');
select ok(not has_table_privilege('anon','public.trip_source_staged_resources','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_staged_resources'::regclass and attnum>0 and not attisdropped and has_column_privilege('anon',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'anon: trip_source_staged_resources no direct or live-column privileges');
select ok(not has_table_privilege('anon','public.trip_source_execution_attempts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_execution_attempts'::regclass and attnum>0 and not attisdropped and has_column_privilege('anon',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'anon: trip_source_execution_attempts no direct or live-column privileges');
select ok(not has_function_privilege('anon','public.trip_source_execution_inventory()','EXECUTE'),'anon: no internal recovery inventory');
select ok(not has_table_privilege('authenticated','public.trip_source_staged_resources','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_staged_resources'::regclass and attnum>0 and not attisdropped and has_column_privilege('authenticated',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'authenticated: trip_source_staged_resources no direct or live-column privileges');
select ok(not has_table_privilege('authenticated','public.trip_source_execution_attempts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_execution_attempts'::regclass and attnum>0 and not attisdropped and has_column_privilege('authenticated',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'authenticated: trip_source_execution_attempts no direct or live-column privileges');
select ok(not has_function_privilege('authenticated','public.trip_source_execution_inventory()','EXECUTE'),'authenticated: no internal recovery inventory');
select ok(not has_table_privilege('service_role','public.trip_source_staged_resources','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_staged_resources'::regclass and attnum>0 and not attisdropped and has_column_privilege('service_role',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'service_role: trip_source_staged_resources no direct or live-column privileges');
select ok(not has_table_privilege('service_role','public.trip_source_execution_attempts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_execution_attempts'::regclass and attnum>0 and not attisdropped and has_column_privilege('service_role',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'service_role: trip_source_execution_attempts no direct or live-column privileges');
select ok(not has_function_privilege('service_role','public.trip_source_execution_inventory()','EXECUTE'),'service_role: no internal recovery inventory');
select ok(not has_table_privilege('otr_trip_source_command_gateway','public.trip_source_staged_resources','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_staged_resources'::regclass and attnum>0 and not attisdropped and has_column_privilege('otr_trip_source_command_gateway',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'otr_trip_source_command_gateway: trip_source_staged_resources no direct or live-column privileges');
select ok(not has_table_privilege('otr_trip_source_command_gateway','public.trip_source_execution_attempts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_execution_attempts'::regclass and attnum>0 and not attisdropped and has_column_privilege('otr_trip_source_command_gateway',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'otr_trip_source_command_gateway: trip_source_execution_attempts no direct or live-column privileges');
select ok(not has_function_privilege('otr_trip_source_command_gateway','public.trip_source_execution_inventory()','EXECUTE'),'otr_trip_source_command_gateway: no internal recovery inventory');
select ok(not has_table_privilege('otr_trip_source_operation_reader','public.trip_source_staged_resources','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_staged_resources'::regclass and attnum>0 and not attisdropped and has_column_privilege('otr_trip_source_operation_reader',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'otr_trip_source_operation_reader: trip_source_staged_resources no direct or live-column privileges');
select ok(not has_table_privilege('otr_trip_source_operation_reader','public.trip_source_execution_attempts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') and not exists(select 1 from pg_attribute where attrelid='public.trip_source_execution_attempts'::regclass and attnum>0 and not attisdropped and has_column_privilege('otr_trip_source_operation_reader',attrelid,attnum,'SELECT,INSERT,UPDATE,REFERENCES')),'otr_trip_source_operation_reader: trip_source_execution_attempts no direct or live-column privileges');
select ok(not has_function_privilege('otr_trip_source_operation_reader','public.trip_source_execution_inventory()','EXECUTE'),'otr_trip_source_operation_reader: no internal recovery inventory');
grant all on public.trip_source_staged_resources,public.trip_source_execution_attempts to anon;set local role anon;
select throws_ok($q$update public.trip_source_staged_resources set id=id where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row update guard trip_source_staged_resources');
select throws_ok($q$insert into public.trip_source_staged_resources select * from public.trip_source_staged_resources where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row insert guard trip_source_staged_resources');
select throws_ok($q$delete from public.trip_source_staged_resources where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row delete guard trip_source_staged_resources');
select throws_ok($q$truncate public.trip_source_staged_resources cascade$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row truncate guard trip_source_staged_resources');
reset role;revoke all on public.trip_source_staged_resources from anon;
grant all on public.trip_source_execution_attempts to anon;set local role anon;
select throws_ok($q$update public.trip_source_execution_attempts set id=id where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row update guard trip_source_execution_attempts');
select throws_ok($q$insert into public.trip_source_execution_attempts select * from public.trip_source_execution_attempts where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row insert guard trip_source_execution_attempts');
select throws_ok($q$delete from public.trip_source_execution_attempts where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row delete guard trip_source_execution_attempts');
select throws_ok($q$truncate public.trip_source_execution_attempts$q$,'P0001','SOURCE_EXECUTION_PROTECTED','anon: zero-row truncate guard trip_source_execution_attempts');
reset role;revoke all on public.trip_source_execution_attempts from anon;
grant all on public.trip_source_staged_resources,public.trip_source_execution_attempts to authenticated;set local role authenticated;
select throws_ok($q$update public.trip_source_staged_resources set id=id where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row update guard trip_source_staged_resources');
select throws_ok($q$insert into public.trip_source_staged_resources select * from public.trip_source_staged_resources where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row insert guard trip_source_staged_resources');
select throws_ok($q$delete from public.trip_source_staged_resources where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row delete guard trip_source_staged_resources');
select throws_ok($q$truncate public.trip_source_staged_resources cascade$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row truncate guard trip_source_staged_resources');
reset role;revoke all on public.trip_source_staged_resources from authenticated;
grant all on public.trip_source_execution_attempts to authenticated;set local role authenticated;
select throws_ok($q$update public.trip_source_execution_attempts set id=id where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row update guard trip_source_execution_attempts');
select throws_ok($q$insert into public.trip_source_execution_attempts select * from public.trip_source_execution_attempts where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row insert guard trip_source_execution_attempts');
select throws_ok($q$delete from public.trip_source_execution_attempts where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row delete guard trip_source_execution_attempts');
select throws_ok($q$truncate public.trip_source_execution_attempts$q$,'P0001','SOURCE_EXECUTION_PROTECTED','authenticated: zero-row truncate guard trip_source_execution_attempts');
reset role;revoke all on public.trip_source_execution_attempts from authenticated;
grant all on public.trip_source_staged_resources,public.trip_source_execution_attempts to service_role;set local role service_role;
select throws_ok($q$update public.trip_source_staged_resources set id=id where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row update guard trip_source_staged_resources');
select throws_ok($q$insert into public.trip_source_staged_resources select * from public.trip_source_staged_resources where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row insert guard trip_source_staged_resources');
select throws_ok($q$delete from public.trip_source_staged_resources where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row delete guard trip_source_staged_resources');
select throws_ok($q$truncate public.trip_source_staged_resources cascade$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row truncate guard trip_source_staged_resources');
reset role;revoke all on public.trip_source_staged_resources from service_role;
grant all on public.trip_source_execution_attempts to service_role;set local role service_role;
select throws_ok($q$update public.trip_source_execution_attempts set id=id where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row update guard trip_source_execution_attempts');
select throws_ok($q$insert into public.trip_source_execution_attempts select * from public.trip_source_execution_attempts where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row insert guard trip_source_execution_attempts');
select throws_ok($q$delete from public.trip_source_execution_attempts where false$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row delete guard trip_source_execution_attempts');
select throws_ok($q$truncate public.trip_source_execution_attempts$q$,'P0001','SOURCE_EXECUTION_PROTECTED','service_role: zero-row truncate guard trip_source_execution_attempts');
reset role;revoke all on public.trip_source_execution_attempts from service_role;
set local role otr_trip_source_execution_writer;
select throws_ok($q$update public.trip_source_operations set id=id where false$q$,'42501','TRIP_SOURCE_COMMANDS_DISABLED','operation lock privilege does not grant canonical DML');
reset role;
select is((select count(*)::int from pg_proc where proowner='otr_trip_source_execution_writer'::regrole),9,'writer owns exactly nine approved routines');
select ok(not exists(select 1 from pg_shdepend where refclassid='pg_authid'::regclass and refobjid='otr_trip_source_execution_gateway'::regrole and deptype='o'),'gateway owns zero objects across all classes/databases');
select ok(not exists(select 1 from pg_namespace where nspname not in ('pg_catalog','information_schema') and nspname !~ '^pg_(toast|temp)' and (has_schema_privilege('otr_trip_source_execution_writer',oid,'CREATE') or has_schema_privilege('otr_trip_source_execution_gateway',oid,'CREATE'))),'no non-system schema CREATE');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'trip_source_execution_%' and has_function_privilege('anon',p.oid,'EXECUTE')),'anon: no effective EXECUTE on any journal routine');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'trip_source_execution_%' and has_function_privilege('authenticated',p.oid,'EXECUTE')),'authenticated: no effective EXECUTE on any journal routine');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'trip_source_execution_%' and has_function_privilege('service_role',p.oid,'EXECUTE')),'service_role: no effective EXECUTE on any journal routine');
select ok(not has_function_privilege('otr_trip_source_execution_gateway','public.trip_source_execution_lock(uuid,uuid,bigint)','EXECUTE'),'gateway cannot execute private lock helper');
select * from finish();
rollback;
