\connect postgres supabase_admin
begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select ok(not (select enabled from public.trip_person_command_gate),'product gate CLOSED');
select is((select generation from public.trip_person_command_gate),0::bigint,'fresh gate generation zero');
select ok(public.trip_person_activation_security_check(true,false),'exact closed foundation security inventory');
select ok(not has_table_privilege('otr_trip_person_command_gateway','public.journey_members','SELECT,UPDATE,INSERT,DELETE'),'gateway no Member read/DML');
select ok(not has_table_privilege('otr_trip_person_command_gateway','public.trip_person_command_gate','SELECT,UPDATE,INSERT,DELETE'),'gateway no gate read/DML');
select ok(not has_table_privilege('otr_trip_person_lifecycle_writer','public.journey_members','UPDATE'),'writer no broad update');
select ok(has_column_privilege('otr_trip_person_lifecycle_writer','public.journey_members','participation_active','UPDATE'),'writer active column');
select ok(has_column_privilege('otr_trip_person_lifecycle_writer','public.journey_members','participation_revision','UPDATE'),'writer revision column');
select ok(not has_column_privilege('otr_trip_person_lifecycle_writer','public.journey_members','role','UPDATE'),'writer cannot change role/access');
select ok((select bool_and(not rolcanlogin and not rolsuper and not rolcreatedb and not rolcreaterole and not rolinherit and not rolbypassrls and not rolreplication) from pg_roles where rolname in ('otr_trip_person_command_gateway','otr_trip_person_lifecycle_writer','otr_trip_person_receipt_reader')),'reserved attributes / no LOGIN credential');
select is((select count(*)::int from pg_auth_members where member='otr_trip_person_command_gateway'::regrole or roleid='otr_trip_person_command_gateway'::regrole and (member<>'postgres'::regrole or set_option or inherit_option)),0,'gateway no application/SET/inherited membership path');
select is((select count(*)::int from pg_shdepend where refobjid='otr_trip_person_command_gateway'::regrole and deptype='o'),0,'gateway no ownership/DDL');
select ok(not has_schema_privilege('otr_trip_person_command_gateway','public','CREATE'),'no public schema CREATE');
select ok((select bool_and(not has_function_privilege(x.role_name,f.signature,'EXECUTE')) from unnest(array['anon','authenticated','service_role']) x(role_name) cross join unnest(array['public.trip_person_runtime_state()','public.trip_person_set_command_gate(bigint,boolean)','public.trip_person_activation_security_check(boolean,boolean)']) f(signature)),'no API/PUBLIC EXECUTE leakage');
set session authorization otr_trip_person_command_gateway;
select is(public.trip_person_runtime_state(),'{"commandVersion":1,"receiptVersion":1,"gateClosed":true,"gateGeneration":0,"schemaVersion":"20261005000200"}'::jsonb,'fixed discovery facts only');
select is(public.trip_person_receipt_lookup('00000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','ac500000-0000-4000-8000-000000000001'),null::jsonb,'own absent exact receipt remains null');
select throws_ok($q$select public.trip_person_receipt_lookup('00000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000001','ac500000-0000-4000-8000-000000000001')$q$,'42501','PARTICIPATION_FORBIDDEN','nonorganizer no disclosure');
select throws_ok($q$select public.trip_person_set_command_gate(0,true)$q$,'42501',null,'gateway no admin setter');
select throws_ok($q$set role otr_trip_person_lifecycle_writer$q$,'42501',null,'gateway cannot SET ROLE writer');
select throws_ok($q$update public.trip_person_command_gate set enabled=true,generation=1$q$,'42501',null,'gateway cannot write gate');
select throws_ok($q$delete from public.trip_person_command_gate$q$,'42501',null,'gateway cannot delete gate');
select throws_ok($q$truncate public.trip_person_command_gate$q$,'42501',null,'gateway cannot truncate gate');
reset session authorization;
set session authorization service_role;
select set_config('request.jwt.claims','{"role":"otr_trip_person_command_gateway"}',true);
select set_config('otr.participation_commands_enabled','true',true);
select throws_ok($q$select public.trip_person_runtime_state()$q$,'42501',null,'service/JWT/GUC cannot discover');
select throws_ok($q$select public.trip_person_set_command_gate(0,true)$q$,'42501',null,'service no admin setter');
select throws_ok($q$set role otr_trip_person_command_gateway$q$,'42501',null,'service cannot SET ROLE gateway');
select throws_ok($q$update public.trip_person_command_gate set enabled=true,generation=1$q$,'42501',null,'service cannot write gate');
reset session authorization;
set session authorization authenticated;
select throws_ok($q$select public.trip_person_runtime_state()$q$,'42501',null,'app no discovery execute');
select throws_ok($q$set role otr_trip_person_command_gateway$q$,'42501',null,'app cannot SET ROLE gateway');
select throws_ok($q$update public.trip_person_command_gate set enabled=true,generation=1$q$,'42501',null,'app cannot write gate');
reset session authorization;
set session authorization postgres;
select is(public.trip_person_set_command_gate(0,true),'{"gateClosed":false,"gateGeneration":1}'::jsonb,'local admin OPEN + generation');
select throws_ok($q$select public.trip_person_set_command_gate(0,false)$q$,'40001','PARTICIPATION_GATE_GENERATION_CONFLICT','stale fence denied');
select is(public.trip_person_set_command_gate(1,false),'{"gateClosed":true,"gateGeneration":2}'::jsonb,'local admin CLOSE + generation');
select is(public.trip_person_set_command_gate(2,true),'{"gateClosed":false,"gateGeneration":3}'::jsonb,'ABA advances generation');
select throws_ok($q$select public.trip_person_set_command_gate(1,false)$q$,'40001','PARTICIPATION_GATE_GENERATION_CONFLICT','old OPEN fence cannot win after ABA');
select is(public.trip_person_set_command_gate(3,false),'{"gateClosed":true,"gateGeneration":4}'::jsonb,'close test scope');
select is(public.trip_person_set_command_gate(4,false),'{"gateClosed":true,"gateGeneration":5}'::jsonb,'same-state administrative transition also fences');
select throws_ok($q$update public.trip_person_command_gate set enabled=true$q$,'42501','PARTICIPATION_GATE_TRANSITION_INVALID','raw stale generation cannot bypass guard');
reset session authorization;
-- Definition corruption cannot be advertised as compatible installed v1.
create temporary table ai2c5_lookup_definition as select pg_get_functiondef('public.trip_person_receipt_lookup(uuid,uuid,uuid)'::regprocedure) definition;
create or replace function public.trip_person_receipt_lookup(actor uuid,trip uuid,operation uuid) returns jsonb
language plpgsql stable security definer set search_path=pg_catalog as $$ begin return null; end $$;
set session authorization otr_trip_person_command_gateway;
select throws_ok($q$select public.trip_person_runtime_state()$q$,'P0001','UNSAFE_PARTICIPATION_ACTIVATION_DEPENDENCY','corrupt receipt definition fails closed');
reset session authorization;
do $$ begin execute (select definition from ai2c5_lookup_definition); end $$;
grant update(display_name) on public.journey_members to otr_trip_person_lifecycle_writer;
set session authorization postgres;
select throws_ok($q$select public.trip_person_set_command_gate(5,true)$q$,'P0001',null,'polluted writer rights cannot open gate');
reset session authorization;
revoke update(display_name) on public.journey_members from otr_trip_person_lifecycle_writer;
select ok(not (select enabled from public.trip_person_command_gate) and (select generation from public.trip_person_command_gate)=5,'failed open leaves closed generation intact');
-- Reserve one final generation for CLOSE; exhaustion can never leave OPEN.
alter table public.trip_person_command_gate disable trigger trip_person_command_gate_transition;
update public.trip_person_command_gate set enabled=false,generation=9007199254740990;
alter table public.trip_person_command_gate enable trigger trip_person_command_gate_transition;
set session authorization postgres;
select throws_ok($q$select public.trip_person_set_command_gate(9007199254740990,true)$q$,'P0001','PARTICIPATION_GATE_GENERATION_EXHAUSTED','OPEN must reserve CLOSE capacity');
select is(public.trip_person_set_command_gate(9007199254740990,false),'{"gateClosed":true,"gateGeneration":9007199254740991}'::jsonb,'final generation stays CLOSED');
reset session authorization;
-- Missing/corrupt state cannot implicitly reinitialize/open. Trusted fixture only.
alter table public.trip_person_command_gate disable trigger trip_person_command_gate_transition;
delete from public.trip_person_command_gate;
alter table public.trip_person_command_gate enable trigger trip_person_command_gate_transition;
set session authorization otr_trip_person_command_gateway;
select throws_ok($q$select public.trip_person_runtime_state()$q$,'P0001','REPLAY_UNAVAILABLE','missing discovery fail closed');
reset session authorization;
set session authorization postgres;
select throws_ok($q$select public.trip_person_set_command_gate(5,true)$q$,'P0001','PARTICIPATION_COMMANDS_DISABLED','missing gate cannot implicitly open');
reset session authorization;
select * from finish();
rollback;
