\connect postgres supabase_admin
begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_runs'::regclass),'trip_source_runs RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_runs','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_runs');
select ok(not has_table_privilege('authenticated','public.trip_source_runs','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_runs');
select ok(not has_table_privilege('service_role','public.trip_source_runs','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_runs');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_inputs'::regclass),'trip_source_inputs RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_inputs','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_inputs');
select ok(not has_table_privilege('authenticated','public.trip_source_inputs','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_inputs');
select ok(not has_table_privilege('service_role','public.trip_source_inputs','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_inputs');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_candidates'::regclass),'trip_source_candidates RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_candidates','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_candidates');
select ok(not has_table_privilege('authenticated','public.trip_source_candidates','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_candidates');
select ok(not has_table_privilege('service_role','public.trip_source_candidates','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_candidates');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_confirmations'::regclass),'trip_source_confirmations RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_confirmations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_confirmations');
select ok(not has_table_privilege('authenticated','public.trip_source_confirmations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_confirmations');
select ok(not has_table_privilege('service_role','public.trip_source_confirmations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_confirmations');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_output_slots'::regclass),'trip_source_output_slots RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_output_slots','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_output_slots');
select ok(not has_table_privilege('authenticated','public.trip_source_output_slots','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_output_slots');
select ok(not has_table_privilege('service_role','public.trip_source_output_slots','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_output_slots');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_associations'::regclass),'trip_source_associations RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_associations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_associations');
select ok(not has_table_privilege('authenticated','public.trip_source_associations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_associations');
select ok(not has_table_privilege('service_role','public.trip_source_associations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_associations');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_run_predecessors'::regclass),'trip_source_run_predecessors RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_run_predecessors','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_run_predecessors');
select ok(not has_table_privilege('authenticated','public.trip_source_run_predecessors','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_run_predecessors');
select ok(not has_table_privilege('service_role','public.trip_source_run_predecessors','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_run_predecessors');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_candidate_lineage'::regclass),'trip_source_candidate_lineage RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_candidate_lineage','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_candidate_lineage');
select ok(not has_table_privilege('authenticated','public.trip_source_candidate_lineage','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_candidate_lineage');
select ok(not has_table_privilege('service_role','public.trip_source_candidate_lineage','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_candidate_lineage');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_slot_lineage_dispositions'::regclass),'trip_source_slot_lineage_dispositions RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_slot_lineage_dispositions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_slot_lineage_dispositions');
select ok(not has_table_privilege('authenticated','public.trip_source_slot_lineage_dispositions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_slot_lineage_dispositions');
select ok(not has_table_privilege('service_role','public.trip_source_slot_lineage_dispositions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_slot_lineage_dispositions');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_source_slot_dependencies'::regclass),'trip_source_slot_dependencies RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_source_slot_dependencies','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_source_slot_dependencies');
select ok(not has_table_privilege('authenticated','public.trip_source_slot_dependencies','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_source_slot_dependencies');
select ok(not has_table_privilege('service_role','public.trip_source_slot_dependencies','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_source_slot_dependencies');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.itinerary_transport_services'::regclass),'itinerary_transport_services RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.itinerary_transport_services','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied itinerary_transport_services');
select ok(not has_table_privilege('authenticated','public.itinerary_transport_services','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied itinerary_transport_services');
select ok(not has_table_privilege('service_role','public.itinerary_transport_services','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied itinerary_transport_services');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.trip_import_admission_gate'::regclass),'trip_import_admission_gate RLS ENABLE/FORCE');
select ok(not has_table_privilege('anon','public.trip_import_admission_gate','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon denied trip_import_admission_gate');
select ok(not has_table_privilege('authenticated','public.trip_import_admission_gate','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated denied trip_import_admission_gate');
select ok(not has_table_privilege('service_role','public.trip_import_admission_gate','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role denied trip_import_admission_gate');
select ok((select not rolcanlogin and not rolsuper and not rolcreaterole and not rolcreatedb and not rolreplication and not rolbypassrls from pg_roles where rolname='otr_trip_source_writer'),'otr_trip_source_writer isolated flags');
select ok(not has_schema_privilege('otr_trip_source_writer','public','CREATE'),'otr_trip_source_writer no schema CREATE');
select ok(not exists(select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='otr_trip_source_writer')),'otr_trip_source_writer no outgoing membership');
select ok(not exists(select 1 from pg_default_acl where defaclrole=(select oid from pg_roles where rolname='otr_trip_source_writer')),'otr_trip_source_writer no default grant');
select ok((select not rolcanlogin and not rolsuper and not rolcreaterole and not rolcreatedb and not rolreplication and not rolbypassrls from pg_roles where rolname='otr_trip_source_command_gateway'),'otr_trip_source_command_gateway isolated flags');
select ok(not has_schema_privilege('otr_trip_source_command_gateway','public','CREATE'),'otr_trip_source_command_gateway no schema CREATE');
select ok(not exists(select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='otr_trip_source_command_gateway')),'otr_trip_source_command_gateway no outgoing membership');
select ok(not exists(select 1 from pg_default_acl where defaclrole=(select oid from pg_roles where rolname='otr_trip_source_command_gateway')),'otr_trip_source_command_gateway no default grant');
select ok((select not rolcanlogin and not rolsuper and not rolcreaterole and not rolcreatedb and not rolreplication and not rolbypassrls from pg_roles where rolname='otr_trip_source_operation_reader'),'otr_trip_source_operation_reader isolated flags');
select ok(not has_schema_privilege('otr_trip_source_operation_reader','public','CREATE'),'otr_trip_source_operation_reader no schema CREATE');
select ok(not exists(select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='otr_trip_source_operation_reader')),'otr_trip_source_operation_reader no outgoing membership');
select ok(not exists(select 1 from pg_default_acl where defaclrole=(select oid from pg_roles where rolname='otr_trip_source_operation_reader')),'otr_trip_source_operation_reader no default grant');
select ok((select not rolcanlogin and not rolsuper and not rolcreaterole and not rolcreatedb and not rolreplication and not rolbypassrls from pg_roles where rolname='otr_trip_event_semantic_writer'),'otr_trip_event_semantic_writer isolated flags');
select ok(not has_schema_privilege('otr_trip_event_semantic_writer','public','CREATE'),'otr_trip_event_semantic_writer no schema CREATE');
select ok(not exists(select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='otr_trip_event_semantic_writer')),'otr_trip_event_semantic_writer no outgoing membership');
select ok(not exists(select 1 from pg_default_acl where defaclrole=(select oid from pg_roles where rolname='otr_trip_event_semantic_writer')),'otr_trip_event_semantic_writer no default grant');
select ok((select not rolcanlogin and not rolsuper and not rolcreaterole and not rolcreatedb and not rolreplication and not rolbypassrls from pg_roles where rolname='otr_trip_event_command_gateway'),'otr_trip_event_command_gateway isolated flags');
select ok(not has_schema_privilege('otr_trip_event_command_gateway','public','CREATE'),'otr_trip_event_command_gateway no schema CREATE');
select ok(not exists(select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='otr_trip_event_command_gateway')),'otr_trip_event_command_gateway no outgoing membership');
select ok(not exists(select 1 from pg_default_acl where defaclrole=(select oid from pg_roles where rolname='otr_trip_event_command_gateway')),'otr_trip_event_command_gateway no default grant');
select ok((select not rolcanlogin and not rolsuper and not rolcreaterole and not rolcreatedb and not rolreplication and not rolbypassrls from pg_roles where rolname='otr_trip_event_receipt_reader'),'otr_trip_event_receipt_reader isolated flags');
select ok(not has_schema_privilege('otr_trip_event_receipt_reader','public','CREATE'),'otr_trip_event_receipt_reader no schema CREATE');
select ok(not exists(select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='otr_trip_event_receipt_reader')),'otr_trip_event_receipt_reader no outgoing membership');
select ok(not exists(select 1 from pg_default_acl where defaclrole=(select oid from pg_roles where rolname='otr_trip_event_receipt_reader')),'otr_trip_event_receipt_reader no default grant');
select ok(not exists(select 1 from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('trip_import_json_valid','trip_import_scope_lock','trip_import_require_gate','trip_import_input_valid','trip_import_lineage_candidates','trip_import_claim_check','trip_import_catalog_write_guard','trip_import_catalog_scope_guard','trip_import_field_value','trip_import_locators_valid','trip_source_publish_flight_run','trip_source_prepare_confirmation','trip_source_mark_slot_dispatch','trip_event_receipt_for_source_slot','trip_source_admit_event_operation','trip_source_admit_event_proof','trip_source_finalize_event_slot','trip_flight_services_valid','trip_flight_endpoint','trip_flight_payload_keys','trip_event_execute_flight','trip_event_create_transport','trip_event_update_transport','trip_source_lock_scope','trip_import_lock_admission','guard_trip_import_services','assert_trip_flight_services','validate_trip_flight_services','trip_source_read_event_services','trip_import_observation','trip_source_read_import_catalogs','trip_import_run_input_hash','trip_import_field_key_valid','trip_import_value_valid','trip_import_review_valid','trip_source_revoke_undispatched_slot') and exists(select 1 from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where a.privilege_type='EXECUTE' and (a.grantee=0 or a.grantee in(select oid from pg_roles where rolname in ('anon','authenticated','service_role'))))),'all import roots deny API/PUBLIC execute');
select ok(not exists(select 1 from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('trip_import_json_valid','trip_import_scope_lock','trip_import_require_gate','trip_import_input_valid','trip_import_lineage_candidates','trip_import_claim_check','trip_import_catalog_write_guard','trip_import_catalog_scope_guard','trip_import_field_value','trip_import_locators_valid','trip_source_publish_flight_run','trip_source_prepare_confirmation','trip_source_mark_slot_dispatch','trip_event_receipt_for_source_slot','trip_source_admit_event_operation','trip_source_admit_event_proof','trip_source_finalize_event_slot','trip_flight_services_valid','trip_flight_endpoint','trip_flight_payload_keys','trip_event_execute_flight','trip_event_create_transport','trip_event_update_transport','trip_source_lock_scope','trip_import_lock_admission','guard_trip_import_services','assert_trip_flight_services','validate_trip_flight_services','trip_source_read_event_services','trip_import_observation','trip_source_read_import_catalogs','trip_import_run_input_hash','trip_import_field_key_valid','trip_import_value_valid','trip_import_review_valid','trip_source_revoke_undispatched_slot') and p.proconfig is distinct from array['search_path=pg_catalog']),'all import function search paths fixed');
select ok(has_function_privilege('otr_trip_event_semantic_writer','public.trip_source_admit_event_proof(uuid,uuid,uuid,uuid,text,bigint,text,uuid,uuid,text,jsonb)','EXECUTE'),'B writer fixed proof edge');
select ok(not has_function_privilege('otr_trip_event_semantic_writer','public.trip_source_admit_event_operation(uuid,uuid,uuid,uuid,text,bigint,text)','EXECUTE'),'B cannot bypass proof root');
select ok(not has_function_privilege('otr_trip_source_command_gateway','public.trip_event_create_transport(uuid,uuid,uuid,uuid,text)','EXECUTE'),'C gateway no B mutation');
select ok(not has_function_privilege('otr_trip_source_writer','public.trip_event_update_transport(uuid,uuid,uuid,uuid,bigint,text)','EXECUTE'),'C writer no generic B execution');
select ok(not has_table_privilege('otr_trip_event_semantic_writer','public.trip_source_output_slots','SELECT,INSERT,UPDATE,DELETE'),'B writer no C catalog');
select ok(not has_table_privilege('otr_trip_source_writer','public.trip_event_operation_receipts','SELECT,INSERT,UPDATE,DELETE'),'C writer no raw receipt');
select is((select flight_admission_enabled from trip_import_admission_gate),false,'flight structurally CLOSED');
select is((select capture_admission_enabled from trip_import_admission_gate),false,'Capture structurally CLOSED');
select ok(public.trip_person_activation_security_check(true,false),'A1-I2C5 verifier unchanged');
select * from finish();
rollback;
