-- Read-only CP13A.2 inventory; no provisioning, gate setter or runtime credentials.
set search_path=pg_catalog;
select jsonb_build_object(
 'version',1,'server_migrations',82,'sqlite_migration',49,
 'closed_gates',(select to_jsonb(g) from public.trip_import_admission_gate g),
 'participation_security_verifier',public.trip_person_activation_security_check(true,false),
 'roles',(select jsonb_agg(jsonb_build_object('name',rolname,'login',rolcanlogin,'superuser',rolsuper,'inherit',rolinherit,'create_role',rolcreaterole,'create_db',rolcreatedb,'replication',rolreplication,'bypass_rls',rolbypassrls,'config',rolconfig) order by rolname) from pg_roles where rolname in ('otr_trip_source_writer','otr_trip_source_command_gateway','otr_trip_source_operation_reader','otr_trip_event_semantic_writer','otr_trip_event_command_gateway','otr_trip_event_receipt_reader')),
 'memberships',(select coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'member',u.rolname,'grantor',g.rolname,'admin',m.admin_option,'inherit',m.inherit_option,'set',m.set_option) order by r.rolname,u.rolname),'[]') from pg_auth_members m join pg_roles r on r.oid=m.roleid join pg_roles u on u.oid=m.member join pg_roles g on g.oid=m.grantor where r.rolname in ('otr_trip_source_writer','otr_trip_source_command_gateway','otr_trip_source_operation_reader','otr_trip_event_semantic_writer','otr_trip_event_command_gateway','otr_trip_event_receipt_reader') or u.rolname in ('otr_trip_source_writer','otr_trip_source_command_gateway','otr_trip_source_operation_reader','otr_trip_event_semantic_writer','otr_trip_event_command_gateway','otr_trip_event_receipt_reader')),
 'functions',(select jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'owner',r.rolname,'security_definer',p.prosecdef,'search_path',p.proconfig,'definition_sha256',encode(extensions.digest(pg_get_functiondef(p.oid),'sha256'),'hex'),'acl',p.proacl,'execute_matrix',(select jsonb_object_agg(rolname,has_function_privilege(rolname,p.oid,'EXECUTE')) from pg_roles where rolname in ('otr_trip_source_writer','otr_trip_source_command_gateway','otr_trip_source_operation_reader','otr_trip_event_semantic_writer','otr_trip_event_command_gateway','otr_trip_event_receipt_reader','anon','authenticated','service_role'))) order by p.oid::regprocedure::text) from pg_proc p join pg_roles r on r.oid=p.proowner where p.pronamespace='public'::regnamespace and p.proname in ('trip_import_json_valid','trip_import_scope_lock','trip_import_require_gate','trip_import_input_valid','trip_import_lineage_candidates','trip_import_claim_check','trip_import_catalog_write_guard','trip_import_catalog_scope_guard','trip_import_field_value','trip_import_locators_valid','trip_source_publish_flight_run','trip_source_prepare_confirmation','trip_source_mark_slot_dispatch','trip_event_receipt_for_source_slot','trip_source_admit_event_operation','trip_source_admit_event_proof','trip_source_finalize_event_slot','trip_flight_services_valid','trip_flight_endpoint','trip_flight_payload_keys','trip_event_execute_flight','trip_event_create_transport','trip_event_update_transport','trip_source_lock_scope','trip_import_lock_admission','guard_trip_import_services','assert_trip_flight_services','validate_trip_flight_services','trip_source_read_event_services','trip_import_observation','trip_source_read_import_catalogs','trip_import_run_input_hash','trip_import_field_key_valid','trip_import_value_valid','trip_import_review_valid','trip_source_revoke_undispatched_slot')),
 'tables',(select jsonb_agg(jsonb_build_object('name',c.relname,'owner',r.rolname,'rls_enabled',c.relrowsecurity,'rls_forced',c.relforcerowsecurity,'acl',c.relacl,
 'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'acl',a.attacl,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped),
 'constraints',(select coalesce(jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid)) order by conname),'[]') from pg_constraint where conrelid=c.oid),
 'indexes',(select coalesce(jsonb_agg(indexdef order by indexname),'[]') from pg_indexes where schemaname='public' and tablename=c.relname),
 'policies',(select coalesce(jsonb_agg(jsonb_build_object('name',policyname,'roles',roles,'command',cmd,'using',qual,'check',with_check) order by policyname),'[]') from pg_policies where schemaname='public' and tablename=c.relname)) order by c.relname) from pg_class c join pg_roles r on r.oid=c.relowner where c.relnamespace='public'::regnamespace and c.relname in ('trip_sources','trip_source_revisions','trip_source_representations','itinerary_events','trip_event_operation_receipts','trip_source_runs','trip_source_inputs','trip_source_candidates','trip_source_confirmations','trip_source_output_slots','trip_source_associations','trip_source_run_predecessors','trip_source_candidate_lineage','trip_source_slot_lineage_dispositions','trip_source_slot_dependencies','itinerary_transport_services','trip_import_admission_gate')));
