import type {
  PrototypeDraft,
  PrototypeExpense,
  PrototypeJourneyContext,
  PrototypeMemberBalance,
  PrototypeMember,
  PrototypeSettlementTransfer,
} from "./types";

export const prototypeBalances: PrototypeMemberBalance[] = [
  { memberId: "leon", name: "Leon", amountMinor: 18345 },
  { memberId: "may", name: "May", amountMinor: 12000 },
  { memberId: "mum", name: "Mum", amountMinor: -6215 },
  { memberId: "dad", name: "Dad", amountMinor: -14820 },
  { memberId: "mia", name: "Mia", amountMinor: -9310 },
];

export const prototypeJourneys: PrototypeJourneyContext[] = [
  {
    id: "europe-2026",
    title: "Europe 2026",
    dates: "1 Sep - 18 Sep",
    status: "ACTIVE",
    memberCount: 5,
    settlementCurrency: "NZD",
    mySpendMinor: 184260,
    groupSpendMinor: 642325,
    outstandingMinor: 18345,
  },
  {
    id: "south-island-2026",
    title: "South Island Weekend",
    dates: "10 Sep - 13 Sep",
    status: "ACTIVE",
    memberCount: 3,
    settlementCurrency: "NZD",
    mySpendMinor: 28640,
    groupSpendMinor: 76320,
    outstandingMinor: -4200,
  },
  {
    id: "japan-2027",
    title: "Japan 2027",
    dates: "3 Apr - 16 Apr 2027",
    status: "UPCOMING",
    memberCount: 4,
    settlementCurrency: "NZD",
    mySpendMinor: 0,
    groupSpendMinor: 0,
    outstandingMinor: 0,
  },
  {
    id: "tmb-2026",
    title: "TMB 2026",
    dates: "8 Jun - 20 Jun",
    status: "PAST",
    memberCount: 6,
    settlementCurrency: "NZD",
    mySpendMinor: 236880,
    groupSpendMinor: 918420,
    outstandingMinor: 0,
  },
];

export const prototypeMembers: PrototypeMember[] = [
  {
    id: "leon",
    name: "Leon Lee",
    shortName: "Leon",
    householdId: "lee-family",
    memberShare: 1,
    color: "#087F5B",
  },
  {
    id: "may",
    name: "May Chen",
    shortName: "May",
    householdId: "lee-family",
    memberShare: 1,
    color: "#3867D6",
  },
  {
    id: "mum",
    name: "Mum",
    shortName: "Mum",
    householdId: "parents",
    memberShare: 1,
    color: "#A15C00",
  },
  {
    id: "dad",
    name: "Dad",
    shortName: "Dad",
    householdId: "parents",
    memberShare: 1,
    color: "#7748A8",
  },
  {
    id: "mia",
    name: "Mia",
    shortName: "Mia",
    householdId: "lee-family",
    memberShare: 0.5,
    color: "#C9342F",
  },
];

const audit = (id: string, title: string, detail: string, at: string) => ({
  id,
  title,
  detail,
  at,
});

export const prototypeExpenses: PrototypeExpense[] = [
  {
    id: "expense-eur-card",
    title: "Dinner at Chez Janou",
    category: "Food & Drink",
    occurredAt: "8 Sep, 7:42 pm",
    payerMemberId: "leon",
    merchant: { minor: 10000, currency: "EUR" },
    settlement: { minor: 19780, currency: "NZD" },
    valuationPolicy: "REFERENCE_RATE",
    rateLabel: "1 EUR = 1.9780 NZD · ECB reference",
    splitLabel: "5 people equally",
    splits: ["leon", "may", "mum", "dad", "mia"].map((memberId, index) => ({
      memberId,
      merchantMinor: 2000,
      settlementMinor: index === 0 ? 3956 : 3956,
    })),
    paymentRecord: {
      instrumentLabel: "Visa NZ",
      posted: { minor: 19943, currency: "NZD" },
      postedDate: "10 Sep",
      fee: { minor: 200, currency: "NZD" },
    },
    receiptAttached: true,
    location: "4th arrondissement, Paris",
    notes: "Group dinner after the Marais walk.",
    status: "SYNCED",
    audit: [
      audit("a1", "Expense created", "Leon · equal split", "8 Sep, 7:44 pm"),
      audit("a2", "Receipt attached", "Photo upload complete", "8 Sep, 7:45 pm"),
      audit("a3", "Card posting added", "Visa NZ · NZD 199.43", "10 Sep, 9:12 am"),
    ],
  },
  {
    id: "expense-family",
    title: "Lake cruise tickets",
    category: "Tickets",
    occurredAt: "7 Sep, 10:18 am",
    payerMemberId: "may",
    merchant: { minor: 18400, currency: "EUR" },
    settlement: { minor: 36395, currency: "NZD" },
    valuationPolicy: "REFERENCE_RATE",
    rateLabel: "1 EUR = 1.9780 NZD · Journey reference",
    splitLabel: "Family shares · adults 1, child 0.5",
    splits: [
      { memberId: "leon", merchantMinor: 4089, settlementMinor: 8088 },
      { memberId: "may", merchantMinor: 4089, settlementMinor: 8088 },
      { memberId: "mum", merchantMinor: 4089, settlementMinor: 8088 },
      { memberId: "dad", merchantMinor: 4089, settlementMinor: 8088 },
      { memberId: "mia", merchantMinor: 2044, settlementMinor: 4043 },
    ],
    receiptAttached: true,
    status: "SYNCED",
    audit: [
      audit("a4", "Expense created", "May · household/member shares", "7 Sep, 10:20 am"),
    ],
  },
  {
    id: "expense-taxi",
    title: "Taxi to Gare de Lyon",
    category: "Transport",
    occurredAt: "6 Sep, 6:31 am",
    payerMemberId: "dad",
    merchant: { minor: 4250, currency: "EUR" },
    settlement: { minor: 8407, currency: "NZD" },
    valuationPolicy: "REFERENCE_RATE",
    rateLabel: "1 EUR = 1.9780 NZD · Journey reference",
    splitLabel: "4 people equally · Mia excluded",
    excludedMemberNames: ["Mia"],
    splits: ["leon", "may", "mum", "dad"].map((memberId, index) => ({
      memberId,
      merchantMinor: index < 2 ? 1063 : 1062,
      settlementMinor: index < 3 ? 2102 : 2101,
    })),
    status: "SYNCED",
    audit: [audit("a5", "Expense created", "Dad · Mia excluded", "6 Sep, 6:33 am")],
  },
  {
    id: "expense-dinner",
    title: "Pizza in Naples",
    category: "Food & Drink",
    occurredAt: "4 Sep, 8:16 pm",
    payerMemberId: "mum",
    merchant: { minor: 7850, currency: "EUR" },
    settlement: { minor: 15527, currency: "NZD" },
    valuationPolicy: "REFERENCE_RATE",
    rateLabel: "1 EUR = 1.9780 NZD · Journey reference",
    splitLabel: "5 people equally",
    splits: ["leon", "may", "mum", "dad", "mia"].map((memberId, index) => ({
      memberId,
      merchantMinor: 1570,
      settlementMinor: index < 2 ? 3106 : 3105,
    })),
    status: "SYNCED",
    audit: [audit("a6", "Expense created", "Mum · equal split", "4 Sep, 8:18 pm")],
  },
  {
    id: "expense-offline",
    title: "Museum lockers",
    category: "Other",
    occurredAt: "Today, 11:06 am",
    payerMemberId: "leon",
    merchant: { minor: 1200, currency: "EUR" },
    settlement: { minor: 2374, currency: "NZD" },
    valuationPolicy: "REFERENCE_RATE",
    rateLabel: "Saved Journey rate · 8 Sep",
    splitLabel: "5 people equally",
    splits: ["leon", "may", "mum", "dad", "mia"].map((memberId, index) => ({
      memberId,
      merchantMinor: 240,
      settlementMinor: index < 4 ? 475 : 474,
    })),
    status: "PENDING",
    audit: [
      audit("a7", "Saved on this iPhone", "Waiting for network", "Today, 11:07 am"),
    ],
  },
  {
    id: "expense-conflict",
    title: "Apartment groceries",
    category: "Groceries",
    occurredAt: "3 Sep, 5:40 pm",
    payerMemberId: "may",
    merchant: { minor: 6420, currency: "EUR" },
    settlement: { minor: 12699, currency: "NZD" },
    valuationPolicy: "REFERENCE_RATE",
    rateLabel: "1 EUR = 1.9780 NZD · Journey reference",
    splitLabel: "4 people equally · conflicting edit",
    splits: ["leon", "may", "mum", "dad"].map((memberId, index) => ({
      memberId,
      merchantMinor: 1605,
      settlementMinor: index < 3 ? 3175 : 3174,
    })),
    status: "CONFLICT",
    audit: [
      audit("a8", "Expense created", "May · four participants", "3 Sep, 5:42 pm"),
      audit(
        "a9",
        "Concurrent edit detected",
        "Amount and participants differ",
        "3 Sep, 6:03 pm",
      ),
    ],
  },
];

export const prototypeTransfers: PrototypeSettlementTransfer[] = [
  {
    id: "t1",
    from: "Dad",
    to: "Leon",
    amount: { minor: 14820, currency: "NZD" },
    status: "AWAITING_CONFIRMATION",
    payments: [
      {
        id: "p1",
        paymentAmount: { minor: 6000, currency: "NZD" },
        dischargedAmount: { minor: 6000, currency: "NZD" },
        reportedBy: "Dad",
        paidAt: "9 Sep, 8:14 pm",
        status: "CONFIRMED",
        confirmedBy: "Leon",
        confirmedAt: "9 Sep, 8:22 pm",
      },
      {
        id: "p2",
        paymentAmount: { minor: 4000, currency: "NZD" },
        dischargedAmount: { minor: 4000, currency: "NZD" },
        reportedBy: "Dad",
        paidAt: "10 Sep, 9:10 am",
        status: "CONFIRMED",
        confirmedBy: "Leon",
        confirmedAt: "10 Sep, 9:18 am",
      },
      {
        id: "p3",
        paymentAmount: { minor: 4820, currency: "NZD" },
        dischargedAmount: { minor: 4820, currency: "NZD" },
        reportedBy: "Dad",
        paidAt: "Today, 10:36 am",
        status: "AWAITING_CONFIRMATION",
      },
    ],
  },
  {
    id: "t2",
    from: "Mia",
    to: "May",
    amount: { minor: 9310, currency: "NZD" },
    status: "OPEN",
    payments: [],
  },
  {
    id: "t3",
    from: "Mum",
    to: "Leon",
    amount: { minor: 3525, currency: "NZD" },
    status: "SETTLED",
    payments: [
      {
        id: "p4",
        paymentAmount: { minor: 1782, currency: "EUR" },
        dischargedAmount: { minor: 3525, currency: "NZD" },
        reportedBy: "Mum",
        paidAt: "8 Sep, 6:42 pm",
        status: "CONFIRMED",
        confirmedBy: "Leon",
        confirmedAt: "8 Sep, 7:03 pm",
      },
    ],
  },
  {
    id: "t4",
    from: "Mum",
    to: "May",
    amount: { minor: 2690, currency: "NZD" },
    status: "OPEN",
    payments: [],
  },
];

export const initialPrototypeDraft: PrototypeDraft = {
  amount: "",
  currency: "EUR",
  title: "",
  payerMemberId: "leon",
  participantIds: prototypeMembers.map((member) => member.id),
  splitMode: "EQUAL_PERSON",
  valuationPolicy: "REFERENCE_RATE",
  receiptAttached: false,
  settlementParticipation: "INCLUDED",
};
